### ISSUE TITLE
Improve how data portal is injected via ServiceCollection

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1061]
In version 4.9 I implemented a `DataPortalFactory` concept that is injected into ASP.NET Core pages via `ServiceCollection`.

It would be better to directly inject an `IDataPortal<T>`. To do that it is necessary to [register a generic type for DI](https://www.stevejgordon.co.uk/asp-net-core-dependency-injection-how-to-register-generic-types).

**Comment by dazinator** [comment]
This sounds good.

From a client-side perspective, how would this effect:

1. The way static factory methods are written.
2. The way instance level methods are written that perform DataPortal invocations such as executing commands etc.
3. The way that factory classes are written (i.e purpose built factory rather than using static factory methods on BO)

My guess...

1. Not impacted? (i.e continue to use DataPortal.XYZ directly and forget about IDataPortal<T>)
2. Not impacted? (i.e continue to use DataPortal.XYZ directly and forget about IDataPortal<T>)
3. Use Constructor injection to inject `IDataPortal<YourBO>` into your factory classes.

**Comment by rockfordlhotka** [comment]
Think about this from an ASP.NET Core perspective, using Razor Pages. In that scenario your Razor Page relies on constructor DI to get any dependencies required by the page. Things like an HttpClient or database connection are injected into the page via its ctor.

The idea is to provide an `IDataPortal<T>` instance to the page, so the page can just interact with that data portal instance to create/fetch/update a root domain object of type T.

So no static factory methods - those block too many testing scenarios. Instead your page interacts directly with the dataportal instance.

And this has nothing to do with server-side factory classes. That's entirely unrelated to client-side DI.

**Comment by dazinator** [comment]
> So no static factory methods - those block too many testing scenarios. Instead your page interacts directly with the dataportal instance.

Yep. Having UI layer code interacting directly with a `IDataPortal<T>` may be acceptable for some scenarios / applications. Question 1 and 3 were really centred around what to do when this mechanism is deemed "too loose" from an API perspective - there is no type safety (and therefore intellisense and refactoring support) over how particular business objects can be fetched, for example.

```
DataPortal.Fetch<Customer>(WHAT DO I PUT HERE SPECIFICALLY?)
```

So.. what I typically do, is create a "Factory" class which hides any underlying `IDataPortal<T>` operations but surfaces a tailored API for the business object in question to help the developer along. That way they get decent intellisense etc. 

So my question 1, and 3 were really relating to what this means for such "Factory" classes - and I think I am pretty sure on the answer. I think the enhancement now is that an `IDataPortal<T>` instance can now be injected in to those factory classes, rather than them using the static `DataPortal.XYZ` methods e.g:

```
    public class CustomerFactory // can be registered in ServiceCollection
    {
        private readonly IDataPortal<Customer> _dataPortal;

        public CustomerFactory(IDataPortal<Customer> dataPortal) // dataportal will be resolved from DI.
        {
            _dataPortal = dataPortal;
        }
          
        public Customer Get(string id)
        {
            var crit = new Customer.CustomerFetchCriteria(id);
            return _dataPortal.Fetch(crit); // Previously DataPorta.Fetch<Customer>(crit);  
        }

        public Customer GetByName(string name)
        {
            var crit = new Customer.CustomerFetchCriteria(name);
            return _dataPortal.Fetch(crit); // Previously DataPorta.Fetch<Customer>(crit);        
        }

        public Customer NewCustomer()
        {
            return _dataPortal.Create();
        }

        public static void Delete(string id)
        {
            _dataPortal.Delete(id);
        }
    }

```

Side note: I don't really like the term "Factory" for this style of object, because as you'll notice, this "CustomerFactory" object also has methods for deleting a customer. Factory's are known for object instantiation not deletion.. I'd welcome any suggestions for a better name for this style of object written here if you have one!

Where I am still unclear is question 2 - Business objects themselves sometimes also provide instance level helper methods that use the DataPortal - for example a method that executes a command:

```
        #region Business Methods

        public void DoSomething()
        {
            DataPortal.Execute<DoSomethingCommand>();
        }


```
In this scenario - it doesn't look like there is any choice but to use the static DataPortal instance - as there is no injection of an `IDataPortal<T>` instance into the business object itself on the client side. This looks like it might be problematic - i.e consider following:-

```
IDataPortal<Customer> customDataPortal = CreateCustomDataPortal<Customer>();
var customer = customDataPortal .Fetch("foo");
customer.DoSomeCommand();
```

Here we have created a custom data portal instance. It is used to fetch a customer business object (I could have used a factory class as shown above with that IDataPortal<T> injected if I'd wanted to). However once we have the business object itself, and call some helper method that executes a command - it's going to call CSLA's static DataPortal.Exececute method - and not leverage our custom DataPortal. I don't have a use case for this yet myself, it's just something that occurred to me that I wanted to check.

It seemed to me that ultimately, business objects have two seperate lifecycles, one on the server and one on the client. I have used DI with CSLA in many previous projects. I was recently considering a model where the Business object could have a public constructor - over which client side DI would be leveraged, and a private constructor, which would be used for constructor DI on the server side. This would eliminate the need for method injection into the DataPortal.XYZ methods. I haven't thought a great deal into the details of this yet.

**Comment by rockfordlhotka** [comment]
> It seemed to me that ultimately, business objects have two seperate lifecycles, one on the server and one on the client.

A goal of CSLA is to provide _location transparency_ where the code inside your business classes don't care whether they are on the client or server (or somewhere else).

Outside the class there may be some differences, though I think those should be minimized too. But _inside_ a business class the code generally shouldn't care. And if it does care it should be able to rely on the context to find out its logical execution location.

**Comment by rockfordlhotka** [comment]
The problem with constructor injection is that it forces the business class author to create private fields for non-serializable references (like to the DAL, the data portal, transactions, database connections) so those fields can be set in the ctor and used later in the DP_XYZ methods.

That's a lot of useless plumbing code for the business class developer, and a lot of fields that are only useful for a few milliseconds of the object's life. Worse, developers may forget to mark those fields as non-serializable, resulting in tons of support questions on the forum about serialization exceptions where the DAL or db connection can't be serialized.

Lots of complexity for nothing is what I anticipate.

**Comment by dazinator** [comment]
> Lots of complexity for nothing is what I anticipate.
Good points, I bow to your thinking!

It seems method injection of the DP_XYZ methods on the server side (as already suggested elsewhere) is the best way to go. I'll leave that discussion for the appropriate github issue so I don't cause this issue discussion to veer off track any further :-)


 




So back to method injection of the dp_xyz methods then!

Maybe we can standardise those methods so that the method definition could become part of an interface? For example, what if all dp methods took a context object my deafult.

public void DataPortal_Fetch(CslaContext context)
{
   var sp = context.ServiceProvider;
   var crit = context.
   var myService = sp.GetRequiredService<MyDbContext>();
}

like this then:

In the CSLA base classes a private default constructor is added:

public class BusinessBase
