### ISSUE TITLE
Type is not resolved for member Csla.Security.UnauthenticatedPrincipal

### ISSUE THREAD

**Issue by minhletn** [MarimerLLC/csla#1076]
**Describe the bug**
I got an exception when running unit test, but it works fine when running the Web application

The logic first makes sure user is logged out as below
`Csla.ApplicationContext.User = new UnauthenticatedPrincipal();`

Then it logs them in again, how the exception below occurs on initialising the connection inside DataPortal_Fetch from a SystemConfig class that extends ReadOnlyListBase
`using (SqlConnection cn = new SqlConnection(connectionString))`

`Exception message: Csla.DataPortalException: DataPortal.Fetch failed (DataPortal.Fetch failed (The type initializer for 'System.Data.SqlClient.SqlConnection' threw an exception.)) ---> Csla.Reflection.CallMethodException: CustomIdentity.DataPortal_Fetch method call failed ---> Csla.DataPortalException: DataPortal.Fetch failed (The type initializer for 'System.Data.SqlClient.SqlConnection' threw an exception.) ---> Csla.Reflection.CallMethodException: SystemConfig.DataPortal_Fetch method call failed ---> System.TypeInitializationException: The type initializer for 'System.Data.SqlClient.SqlConnection' threw an exception. ---> System.Runtime.Serialization.SerializationException: Type is not resolved for member 'Csla.Security.UnauthenticatedPrincipal,Csla, Version=4.3.14.0`

we use Microsoft.VisualStudio.TestTools.UnitTesting for unit testing

When I run the Web application and debug the same logic above,
Csla.ApplicationContext.User is also UnauthenticatedPrincipal when the connection is initialised, but does not cause the exception

Does it have anything to do with the CslaDataPortalProxy settings for the unit test project?

**Version and Platform**
CSLA version: 4.3.14
OS: Windows
Platform: WinForms

**Comment by rockfordlhotka** [comment]
You are encountering a known issue with the way unit test frameworks use threads.

The CSLA `ApplicationContext` relies on a provider model, so each runtime environment can manage things like the user identity in a way that is correct for the runtime.

For example, ASP.NET relies on HttpContext, while some smart client environments use a static field and others use System.Threading.Thread.CurrentPrincipal.

The default behavior was in CSLA 4.3 relies on the current thread's CurrentPrincipal. That never works in unit testing environments because the unit testing host (mstest) "reuses" a thread between the host and each individual test.

The solution is to implement a cleanup method in each test class (this is an mstest concept), and in that method make sure to set `ApplicationContext.User` to null. This way when the current thread returns from the test back to the mstest host .NET doesn't attempt to serialize the current principal between environments.

**Comment by rockfordlhotka** [comment]
For future reference I've documented this in the /docs folder.

https://github.com/MarimerLLC/csla/blob/master/docs/unit-testing.md
