### ISSUE TITLE
TransactionTypes enum has mismatch between NS2 and .NET Framework

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/csla#1138]
**Question**
I have .NET Standard 2.0 Business, Dal and DalEf libraries, with a .NET 4.7.2 WinForms UI. I have a saveable `BusinessBindingListBase` decorated with `TransactionScope` similar to the `RoleEditBindingList` in the ProjectTracker example.

``` csharp
[Transactional(TransactionalTypes.TransactionScope)]
protected override void DataPortal_Update()
{
    RaiseListChangedEvents = false;

    using (var ctx = DalFactory.GetManager())
        Child_Update();

    RaiseListChangedEvents = true;
}
```
I'm getting the following exception:

Csla.DataPortalException: DataPortal.Update failed (Specified argument was out of the range of valid values.
Parameter name: transactionalAttribute)

**Version and Platform**
CSLA version: 4.10.0
OS: Windows
Platform: WinForms with .NET Standard 2.0 libraries

**Comment by rockfordlhotka** [comment]
I believe what's happening is that the `TransactionTypes` enum doesn't line up between NS2 and NETfx, because the elements blocked out for NS2 via compiler directive are at the top of the enum, not the bottom.

This can be fixed by using explicit int values for each element, or reordering the elements so the ones only available on NETfx are at the bottom.

**Comment by michaelcsikos** [comment]
Thanks, @rockfordlhotka. Do we have an ETA for the next version?

**Comment by rockfordlhotka** [comment]
No specific timeline for v5.0, because it depends on .NET Core 3, and Microsoft hasn't provided a firm timeline.

I'm happy to accept backports to the 4.x branch - a couple people have backported important fixes from 5.0 already - which reminds me that I need to do a 4.10.1 release this week to get the latest fix out there.

**Comment by michaelcsikos** [comment]
Sounds good. This particular project is in its infancy, but we're planning to release version 0.1 to the client before the end of April, so if we could get this by then or soon after that would be great.

**Comment by rockfordlhotka** [comment]
Happy to take a pull request! 

The FAQ includes a page with instructions on how to [use GitHub to pull down, update, and submit a change](https://github.com/MarimerLLC/csla/blob/master/docs/csla-github-flow.md).

The 4.x branch is called `marimer/v4.x`. The 5.0 branch is `marimer/master`.

**Comment by rockfordlhotka** [comment]
@michaelcsikos sadly this backport wasn't in 4.11.0, but is now in 4.11.1

**Comment by arrayofletters** [comment]
Is there an ETA for this release?  I have a WebApi project that uses .NET Core, a WebForms app on Framework and a Library project on Standard.  This bug precludes me from deploying unless I fix up all 115 references to the attribute.  Which I will then have to change back once 4.11.1 is released.
