### ISSUE TITLE
Implement client UI helpers for Blazor

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1142]
We have UI support types for all the .NET UI frameworks (Windows Forms through ASP.NET Core), and I'm sure we'll need some types to smooth the use of business domain objects that are data bound to a Blazor UI as well.

Right now I don't know what those look like or what's needed, so step 1 of this issue is researching what is needed to make Blazor UI development with CSLA productive and fun.

**Comment by dazinator** [comment]
One area that might be a good starting point is authentication.

In Csla, you authenticate by setting ApplicationContext.User to an IPrincipal.

In Blazor (client side), You authenticate by implementing a custom `AuthenticationProvider` that ultimately returns the current ClaimsPrincipal:

```
class CustomAuthStateProvider : AuthenticationStateProvider
{
    public override Task<AuthenticationState> GetAuthenticationStateAsync()
    {
        var identity = new ClaimsIdentity(new[]
        {
            new Claim(ClaimTypes.Name, "mrfibuli"),
        }, "Fake authentication type");

        var user = new ClaimsPrincipal(identity);

        return Task.FromResult(new AuthenticationState(user));
    }
}

```
Note: where this principal originates from is down to you to manage. You register the provider in your blazor client startup:

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddScoped<AuthenticationStateProvider, CustomAuthStateProvider>();
}
```

This AuthenticationState flows as a cascading parameter through all downstream components in the render tree. Out of the box components like `AuthorizeView` use it to determine which content to render based on if there is an authorised user.

It occurs to me, either developers would need to add some code to their own AuthorisationStateProvider to make sure Csla.ApplicationContext.User is also set to that principal.. or Csla could provide an AuthenticationStateProvider that handles that (developers could perhaps derive from?). Or.. csla could provide a first class component that developers add to their blazor app markup (app.razor) so that it gets included in the render tree, and it can receive the cascading AuthenticationState as a parameter and set Csla.ApplicationContext.User accordingly so no C# code needed. I.e App.Razor would look something like this:


```

<CascadingAuthenticationState>
 <CslaApplicationContext>
    <Router AppAssembly="typeof(Startup).Assembly">
        <NotFoundContent>
            <h1>Sorry</h1>
            <p>Sorry, there's nothing at this address.</p>
        </NotFoundContent>
    </Router>
 <CslaApplicationContext>
</CascadingAuthenticationState>
```

It's quite easy to make a blazor component - I've referred to it above as CslaApplicationContext, that receives the current AuthenticationState and sets Csla.ApplicationContext.User. it can even supply it's own Cascading parameters for downstream components if there are other Csla components that we then want to introduce but require a dependency on this context.

**Comment by rockfordlhotka** [comment]
@dazinator I like your analysis of the authentication concepts.

If I understand the options (plus maybe more)

1. Provide a `CslaAuthenticationStateProvider` that people can derive from, and this base would set the `ApplicationContext.User` property
1. Add an (invisible?) Csla element to the UI render tree so we get the app state (seems hacky?)
1. Provide a `Csla.Blazor.ApplicationContextManager` that implements `GetUser` to pull the current principal from the Blazor context (assuming we can access it from code?)
1. Somehow make the principal available via the `IServiceCollection` so we can get at it via DI

**Comment by dazinator** [comment]
Yup.
**Option 1**  - requires inheritance - not a show stopper but I feel Csla could be more flexible with one of the other options.

**Option 3** seems the most consistent and I like it for that reason. If ApplicationContext now has access to the current IServiceProvider (it seems in v5 it does) then it should be possible to use that to resolve AuthenticationStateProvider and then return the user from it similar to how one might check for HttpContext.User in a web scenario. The implementation though is a bit more complex than option 2, as the AuthenticationStateProvider also has an event you can subscribe to, to get notified when authentication state changes - depending upon the implementation of the AuthenticationStateProvider it might be more efficient to subscribe to this event and grab the principal and store it only when it changes - rather than call `GetAuthenticationStateAsync()` every time Csla.ApplicationContext.User is accessed.. As that runs an Async Task that might even send requests to the backend.. Just one to think about (I.e polling GetAuthenticationState could have bad side effects)

**Option 2**  (invisible component the UI) has some nice things going for it -Specifically it will receive the latest cascaded AuthenticationState - which will be resent automatically whenever the AuthenticationState is changed - this means it doesn't need to access the AuthenticationStateProvider itself or add any event handlers as in option 3. It would be simpler, receiving the auth state as a parameter and setting Csla.ApplicationContext.User from it. I don't see it as hacky as there are already out of the box components that are non visible, and included in the composition of the app, such as `Router` and `CascadingAuthenticationState` - not all components need be visible!

**Option 4**. seems the most hacky to me - more of 'exhausted all other avenues' approach I reckon!

Anyway - will keep thinking on this and will look forward to seeing what you decide to do, if any of the above or something else.

**Comment by TheCakeMonster** [comment]
I think we'll need a validation component that interacts with EditContext, very similar to the DataAnnotationsValidator that has been provided in the box. Whilst CSLA supports data annotations, to get the full power of dependent properties, multiple rulesets and the more advanced features that CSLA's validation offers, we need to go beyond what the validator built into .NET Core can support.

I have been working on this, and it's very straightforward, as CSLA already does the heavy lifting. I have working code, and I'm starting to look at how to integrate it into the Csla solution.

The code needs to reference packages that target .NET Standard 2.0, but which are related to .NET Core 3.0 by their version numbers. Csla.Blazor is not named in a way that would encourage me to do this - it's not named to be for a specific .NET Core release.

Should I add the code to a shared project, for example Csla.Web.Shared, and then reference the latter from a new .NET Core 3.0 project, so that we can have assemblies to target different versions of .NET Core in the future? Or is it your intention only to support a single version of .NET Core at a time?

The packages I would need to reference are Microsoft.AspNetCore.Components and Microsoft.AspNetCore.Components.Web, currently at version 3.0.0-preview9.19424.4

**Comment by rockfordlhotka** [comment]
If this is for blazor it should go in the new blazor project.
