### ISSUE TITLE
Can't use Custom Formatter b/c CSLA hard-codes use of MobileFormatter in places

### ISSUE THREAD

**Issue by MTantos1** [MarimerLLC/csla#1297]
**Describe the bug**
Unable to set the Serialization Formatter.

**Version and Platform**
CSLA version: 4.11.2
OS: Windows, iOS
Platform: WPF, MVC, Xamarin

**Code that Fails**
Provide the failing code, ideally an isolated repro of the issue you are encountering.
`Csla.Configuration.ConfigurationManager.AppSettings["CslaSerializationFormatter"] = "CslaTest.TestFormatter, CslaTest";`
It is my understanding that the above code should set the serialiser to use between the client and server to `TestFormatter`.
TestFormatter implements Csla.Serialization.ISerializationFormatter (`TestFormatter : Csla.Serialization.ISerializationFormatter`)

However, neither the client nor the server instantiate a TestFormatter object or call it's Serialize/Deserialize methods.
The following unit test code, however, passes:

```
Assert.AreEqual(ApplicationContext.SerializationFormatters.CustomFormatter, ApplicationContext.SerializationFormatter);
var serialiser = Csla.Serialization.SerializationFormatterFactory.GetFormatter();
Assert.IsInstanceOfType(serialiser, typeof(TestFormatter));
```

**Stack Trace or Exception Detail**
Provide a stack trace, or at least detailed information about the exception.

**Additional context**
We have a WPF client and iOS (Xamarin) client connecting via HttpProxy to an asp.net MVC5 host.

**Comment by rockfordlhotka** [comment]
You can check to see if the correct formatter is being created this way:

```c#
  var formatter = Csla.Serialization.SerializationFormatterFactory.GetFormatter();
```

That'll return the `ISerializationFormatter` instance used throughout CSLA.

**Comment by rockfordlhotka** [comment]
The `HttpProxy` is (I believe) hard-coded to use `MobileFormatter`

**Comment by MTantos1** [comment]
Thanks for your prompt response Rocky.

We are trying to accomplish a functional equivalent to `BinaryFormatter` as we have a lot of 'legacy' code which uses fields and expects them to be included in the serialisation stream (as this was the case with WCF, which I believe uses `NDCS`?).

By providing a custom formatter we were trying to keep old 'legacy' classes as is. Write one new class, the formatter, and have it work across multiple platforms / devices. Rather than re-write many classes to make them compliant with the MobileFormatter.

But if I'm understanding you correctly, it looks like re-writing many classes to ensure cross device / platform support is the only way at the moment.

P.S. I wasn't sure whether this was a bug or feature request, but posted as a bug report as the presence of `CslaSerializationFormatter` in `AppSettings` led me to believe this was possible.

**Comment by rockfordlhotka** [comment]
I do think it is a bug - a big complex series of related bugs actually - laziness crept in as we chose to use `MobileFormatter` directly all over the place 😢 

For your specific scenario though, I think there are options.

1. Modernize your domain classes to use managed backing fields (I'd suggest this is preferred, since this is increasingly an assumption on our part as we design new features)
1. _Don't_ modernize your classes, but implement `OnGetState`/`OnSetState` to put all your private backing fields into/out of the serialization stream - thus allowing the use of `MobileFormatter` without major surgery on your code
1. Create your own data portal channel, possibly just like `WcfProxy`, that uses your alternate `BinaryFormatter` equivalent where the existing code uses `MobileFormatter`
1. Submit a PR for `HttpProxy` and the controller in the MVC shared project to change the code to get the formatter from `SerializationFormatterFactory` instead of the hard-coded use of `MobileFormatter`

**Comment by itgoran** [comment]
@rockfordlhotka 
I've stumbled on the same limitation today, but maybe there is another way to achieve what I'm trying.

I have a requirement that our Client application use REST API calls for communication with the server so that javascript client (i.e AureliaJS, Angular, etc...) can use the same endpoints for saving data using json requests.

Is this already feasible and I missed something or JSONSerializationFormatter has to be implemented?

**Comment by rockfordlhotka** [comment]
This is totally realistic. Use the data portal in local mode, so the "server-side" runs on the client, and then implement your DAL to make calls to the API instead of to a database.

**Comment by klk103** [comment]
I ran into this today while updating our business library to use ASP.NET Core hosting: HttpPortal hard-codes MobileFormatter instead of using what the configuration specifies. We have quite a few business objects that aren't compatible with MobileFormatter (mostly because the project used NetDataContractSerializer and WCF when I inherited it, and updating to CSLA best practices wasn't a priority), and I anticipate quite a lot of work ahead to make them compatible. Not hugely difficult, but also not trivial (though kudos to Csla.Analyzers for catching compatibility issues during compile!)

Are there plans to make HttpPortalController compatible with the other serializers, or is it more "if you need it, code it yourself?"

**Comment by angtianqiang** [comment]
@klk103 
I met the same problem, since 4.7.2 upgraded to 5.0.1, I have a lot of unused backup field class cannot serialization, as shown in the code List < DTO. ShortDictDataDto >, set the ConfigurationManager. The AppSettings [" CslaSerializationFormatter "] = "BinaryFormatter" after also is invalid, I don't know is how to deal with you now?


 public class GetDictDataCommand : CommandBase<GetDictDataCommand>
    {

        public static readonly PropertyInfo<List<DTO.ShortDictDataDto>> ValueProperty = RegisterProperty<List<DTO.ShortDictDataDto>>(c => c.Value);
        public List<DTO.ShortDictDataDto> Value
        {
            get { return ReadProperty(ValueProperty); }
            private set
            {
                LoadProperty(ValueProperty, value);
            }
        }
        public static readonly PropertyInfo<string> DictTypeProperty = RegisterProperty<string>(c => c.DictType);
        public string DictType
        {
            get { return ReadProperty(DictTypeProperty); }
            private set
            {
                LoadProperty(DictTypeProperty, value);
            }
        }

            public void ExecuteCore()
            {
           
            }
        protected override void DataPortal_Execute()
        {
                ExecuteCore();
            }

     


            [Create]
            [RunLocal]
            private void Create(string  dictType)
            {
                this.DictType = dictType;
            }
        }

    }

**Comment by MTantos1** [comment]
You could create a 'LegacyBaseClass' as follows. We toyed with the idea and had good results from testing but didn't ended up using it in production as the amount of changes required was still significant and if you want to use the `GraphMerger` class, or `SaveAndMergeAsync()` or `Clone()` methods of BusinessBase<T> you need to use managed backing fields. @rockfordlhotka probably has a much cleaner and elegant solution, but this was our original workaround. Just thought I'd share in case it works for you.

```
[Serializable]
public abstract class LegacyClass<T> : BusinessBase<T>
    where T : LegacyClass<T>
{
    private byte[] Data { get => ReadProperty(DataProperty); set => LoadProperty(DataProperty, value); }
    public static readonly PropertyInfo<byte[]> DataProperty = RegisterProperty<byte[]>(p => p.Data);

    protected byte[] Serialise()
    {
        using (var stream = new MemoryStream())
        {
            var serialiser = Csla.Serialization.SerializationFormatterFactory.GetFormatter();
            serialiser.Serialize(stream, this);
            return stream.ToArray();
        }
    }

    protected T Deserialise()
    {
        using (var stream = new MemoryStream(Data))
        {
            var serialiser = Csla.Serialization.SerializationFormatterFactory.GetFormatter();
            var obj = (T)serialiser.Deserialize(stream);
            return obj;
        }
    }

    protected void UpdateData() { Data = Serialise(); }

    protected override Task<T> SaveAsync(bool forceUpdate, object userState, bool isSync)
    {
        UpdateData(); // ensure data goes to server.
        return base.SaveAsync(forceUpdate, userState, isSync);
    }
}
```

Just remember to update your BusinessObjects to inherit from LegacyBase<T> and update the DataPortal_XYZ and factory methods accordingly.

```
[Serializable]
- public class MyOldClass : BusinessBase<MyOldClass>
+ public class MyOldClass : LegacyBase<MyOldClass>
{
    // Rest of code (properties, business rules, etc) omitted for brevity

    public static MyOldClass GetMyOldClass(MyOldClassSearchCriteria criteria)
    {
        var obj = DataPortal.Fetch<MyOldClass>(criteria);
        return obj.Deserialise();
    }

    protected override void DataPortal_Insert()
    {
        var actualObj = Deserialise();
        // Do whatever you would normally do on insert here (except use actualObj instead of this)
    }

    private void DataPortal_Fetch(MyOldClassSearchCriteria criteria)
    {
        // Do normal data load stuff
        UpdateData(); // ensure data comes back from server
    }
}
```

**Comment by rockfordlhotka** [comment]
I like @MTantos1 idea. I suspect it would be a little easier to override OnGetState and OnSetState to get/set the private field values, but the idea is very sound.

**Comment by angtianqiang** [comment]
tks @rockfordlhotka  tks @MTantos1 

I've inherited the code from the sla.core.mobileobject class and rewrote OnSetState and OnGetState

   public  class BaseEntityDto: Csla.Core.MobileObject
    {

      
        protected override void OnSetState(SerializationInfo info, StateMode mode)
        {
            ID = info.GetValue<Guid>(nameof(ID));
            CreateBy = info.GetValue<string>(nameof(CreateBy));
            CreateByID = info.GetValue<Guid>(nameof(CreateByID));
            CreateOn = info.GetValue<DateTime?>(nameof(CreateOn));
            ModifiedBy = info.GetValue<string>(nameof(ModifiedBy));
            ModifiedByID = info.GetValue<Guid>(nameof(ModifiedByID));
            ModifiedOn = info.GetValue<DateTime?>(nameof(ModifiedOn));


            base.OnSetState(info, mode);
        }
        protected override void OnGetState(SerializationInfo info, StateMode mode)
        {
            info.AddValue((nameof(ID)), ID);
            info.AddValue((nameof(CreateBy)), CreateBy);
            info.AddValue((nameof(CreateByID)), CreateByID);
            info.AddValue((nameof(CreateOn)), CreateOn);
            info.AddValue((nameof(ModifiedBy)), ModifiedBy);
            info.AddValue((nameof(ModifiedByID)), ModifiedByID);
            info.AddValue((nameof(ModifiedOn)), ModifiedOn);


            base.OnGetState(info, mode);
        }


@rockfordlhotka  I have one more question. I need to ask for your help! #849

**Comment by rockfordlhotka** [comment]
The codebase has been updated to avoid the hard-coded use of `MobileFormatter` and now relies on `SerializationFormatterFactory.GetFormatter()` any time a serialization formatter is required.

This _might_ be a breaking change for some .NET Framework users, as the http, grpc, and rabbitmq channels will now use the current formatter, not specifically mobileformatter. In .NET Framework the default formatter is `BinaryFormatter`, and so this is a substantial change.

In all cases, you should consider changing to `MobileFormatter` as your default, because `BinaryFormatter` is obsolete in .NET 5, and NDCS doesn't exist past .NET Framework 4.8.
