### ISSUE TITLE
Add Analyzers for Business Rules

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#1318]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I think there's a couple of analyzers that could be added to CSLA related to business rules:

* A rule that doesn't call `AddOutValue()` or one of the `AddXyzResult()` methods on the given `RuleContext` within `Execute()` seems weird. This arguably should be flagged. No code fix for this one. If so, what should be the severity: informational, warning, or error?
* If a rule is asynchronous and derives from `BusinessRule`, it should be changed to `BusinessRuleAsync`, a new type that was recently added and should be used for asynchronous rules. This should have a code fix that will automatically change the type. What should be the severity: informational, warning, or error?
* All asynchronous rules must call `Complete()` on the given `RuleContext` within `Execute()`. It might be possible to create a code fix that adds a call to `Complete()` as the "last thing" the rule does. Flag as an error.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by JasonBock** [comment]
I was talking to @rockfordlhotka about these analyzers, and here's where I'm at.

The first one that changes an async `BusinessRule` to `BusinessRuleAsync` is now in the branch. However, `BusinessRuleAsync` still has `IsAsync` and `Complete()` on them. My question is, do these members even matter with `BusinessRuleAsync`? 

I think Rocky said he was going to check, but I'm thinking that those members are irrelevant now. That is, there should be no reason to set `IsAsync` to `true` in the constructor and call `Complete()` in `ExecuteAsync()`. By its nature, it **is** asynchronous, so there's no need for them. In fact, if this is true, what I could do is check for usages of these members and flag them for the developer, as they aren't necessary. I may also be able to provide a code fix to remove them.

As a side note, over time these members may be marked as obsolete over a couple of versions of CSLA, but again, it depends on how "true" asynchronous rules are handled.

**Comment by rockfordlhotka** [comment]
### IsAsync

I think the trick is whether the rule is implemented through `IBusinessRuleAsync` or as a subclass of `BusinessRuleAsync`.

The `BusinessRuleAsync` type always returns `true` for `IsAsync`, because ... well, it is obvious right? There's no guarantee that someone manually implementing `IBusinessRuleAsync` would do the same thing - but I rather think that this is an edge case not worth worrying about with an analyzer.

### Complete method

A rule implementing `IBusinessRuleAsync` should _not_ manually call `context.Complete()` because this is [automatically performed when the rule finishes executing](https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Shared/Rules/BusinessRules.cs#L786).

**Comment by JasonBock** [comment]
To be clear, if a rule derives from either `IBusinessRuleAsync` or `BusinessRuleAsync`, I should flag a call to `Complete()` in `ExecuteAsync()` as an error, and provide a code fix to remove it.

`IsAsync` can be ignored.

**Comment by rockfordlhotka** [comment]
Yes.

**Comment by JasonBock** [comment]
Don't forget to make Markdown documentation for the new analyzers.
