### ISSUE TITLE
Blazor example should use CSLA authz rules

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1377]
@dazinator updated the `BlazorExample` sample to include authentication and some authorization.

I believe the authorization relies on Blazor UI support directly against the user's principal, and doesn't leverage authorization rules from the business layer.

Ideally the authorization would rely on per-type rules implemented in the `PersonEdit` class to determine whether the current user is authorized to view/edit a person.

**Comment by dazinator** [comment]
Just thinking this through and here is my take on this.

In the sample at the moment, the page (actually the client side route) is the thing that's authorised. Conceptually a blazor page may or may not contain any Csla objects. Or it could contain multiple (for example displaying different forms or lists on different tabs). Therefore I think the current page level authorisation check that's in place in the sample, by not being bound to any particular Csla root object is as it should be.

So then the question is, how do we render say an EditableRoot on a page, and have that view automatically check for CanEdit permissions etc and display display appropriate bot authorised message based on the EditableRoot authorisation rules.

Well.. I'm not sure of the best approach.. yet. But I'm thinking roughly:
1. Extend the native authorisation system so that we can authorise against  business objects (types, instances). We might be able to do this by registering a custom Csla authorisation policy / provider on startup.
2.  Provide a blazor / razor component that can added to a page, wraps a Csla view model, and uses the native authorization service to authenticate the user agains that Csla business object type / instance of said view model. This component would have parameters for content to display if the user is not authorised to View / Edit / Delete etc.

I see there is an EditForm already developed in the sample. If this was wrapped in such a component above then the whole form would not be displayed if the use didnt have edit permission. However what about field level authorisation- would the edit form need to be extended to do authorisation checks on each field? It would it be down to the developer to provided different display templates for fields that fail authorisation? I'm not clear on this more thoughts needed

r to support authorization against Csla root objects I think we need to approach it not at the page level but at a blazor component level. Multiple blazor components can be included on a page but a blazor component is different from a page because it is bit directly navigated to in the browser - i.e it doesnt have it's own route only the page does. 

With this in mind, I'm thinking we 

e is not necessarily a 1 to 1 relationship between a page and a Csla object. Unless you want to create the concept of top level Csla pages such as EditPage, ViewPage etc etc in which case these pages could be routed to and would expect to Authorize against a given Csla business root object. I'd suggest not doing that though. It might be better to handle this by creating blazor components for that rather than pages.

**Comment by rockfordlhotka** [comment]
I understand what you are saying, but there's a philosophical core to CSLA, which is that all rules are centralized in the business layer.

I'm thinking forward to the ProjectTracker Blazor UI I'll build, and in ProjectTracker _at no point_ are there rules outside the business layer. So, for example, whether a user is allowed to navigate to a form/page/screen that edits a domain object, it is a rule from that domain type that is used to tell the UI if the user has permission.

The idea is that when such a rule changes (and authz are _rules_), a dev shouldn't have to hunt through the business layer _and_ the entire UI to see if a role/claim/permission was met. They go to the business layer, change it, and know that the change automatically impacts _all types of app_ that use the business layer.

In other UI technologies I've always created some UI helpers - usually extending existing platform functionality. For example, in MVC there are authorization helpers that can be used in place of the standard ones - the difference being these helpers rely on the business layer for the rules.

It isn't enough to let the user navigate somewhere and tell them they can't see it - that's cruel! 😄 It is necessary to disable or hide the navigate element so they know they can't go there.

**Comment by dazinator** [comment]
I understand, but im not sure fully.. yet! 😁 perhaps allow me to divulge my thinking a bit more to see if we are actually agreeing! 

Not all pages in my blazor SPA may be CSLA driven. For example if I want to add simple content page to my site - and authorise access to it based on the logged in users roles (e.g "members" can access support docs page) - I shouldn't be forced to create a CSLA business layer for that addition to my site. My philosophy then is that my site should work like a normal blazor website _first_ - but then allow me to add Csla driven UI's (i.e bound to Csla objects) where I need to. If you are in regiment with that then I believe the blazor "page" level authorisation is not something csla need concern itself with. It's the actual point where I want to include a Csla driven portion of UI on a page that I care about Csla authorisation checks happening (I.e at the blazor component level) and the ability to control what to render to a non authorised user. I agree it's cruel to allow users to navigate to a page and then not see anything. I'm not sure that this is an issue for Csla to address either.. I could chose to not render any output for the non authorised user, or I could chose to display a message. That's on the developer.  I create blazor pages to reflect the url navigation space I want for my site - not as a 1 to 1 mapping exercise for Csla use cases. To clarify - it's my view that I should be able to build the equivalent of the entire Csla windows forms sample project tracker application, in one single blazor page using blazor components to achieve that. At the page level I'd not apply any authorisation. Or i'd split it into two pages, with the /login page not having any authorisation and the main page requiring authenticated user. The menu I render on that page will want to take nto account Csla authorisation rules so I cant see menu items for things I shouldn't have permission to access but when I do click on a menu item - it need to navigate me off to any other page it would just display the Csla form in a modal. 

So I guess I'm saying I think its desirable to be able to have a page with multiple sections of UI - some backed by Csla, some not, but all of which display content appropriately honouring their own authorisation requirements, and to adopt that model means Csla authorisation has to be done at a component level not at the page routing / blazor navigation model.

Saying all of that suppose you did have a page like /EditUser that you did want to authorise based on Csla auth rule. If you navigate to that page the blazor router will display its NotAuthorised template. In essence you still get the behaviour you said you dont want - i.e being able to navigate to a page and then not see stuff. This is because all pages are routable. Anyone can copy and paste in the URL to visit that page. So the real issue is about not  displaying a link to the page in the first place, based on some Csla auth rule check. We could create a simple helper for that or get the in built AuthorizeView component to work with Csla auth rules based on object type. Secondly suppose the blazor router now does no csla authorization check when  navigating to that page (which is what I am suggesting) but on that page there is some Csla ui component that does the check and displays the configurable notauthorised message. You end up with the same behaviour - except now it's more flexible because other components can still be rendered on the page that dont require Csla authorisation.

**Comment by dazinator** [comment]
Given the above if I was to pursue this line of thinking I'd do this:

1. Have Csla register a custom authorization policy name provider with the authorisation system on startup. This would allow the native authorization system to tap into Csla business object auth rules at a type level (not instance level) using policy names. For example you could use the standard AuthoriseView with a policy name like this:

```
<AuthorizeView Policy="csla-user-edit">
    <p>You can only see this if you satisfy the "content-editor" policy.</p>
</AuthorizeView>
```

They policy name would use some form of convention - containing enough info to resolve the Csla business object type, and rule that needs to be checked. In the case above its checking that the current principal can edit the User business object type. 

I think that's it? With this one native AuthorizeView component, it can be used to conditionally display links and menu items based on Csla type auth rules. Likewise on pages and within modals (for example, around the EditForm in the current sample) it can not show the content if the user isnt authorised.

**Comment by rockfordlhotka** [comment]
I think we're on the same page - we've both been authorized 😄 

I'm not trying to force the idea that every page uses CSLA authorization. But it needs to be an option, because if someone does build a business app - such as porting from WinForms to Blazor - it needs to be possible to leverage rules from the business layer for page, navigation, display/hiding controls, and enabling/disabling controls. Stuff like that.

I think creating a CSLA authorization policy (or policies?) that use per-type rules is absolutely the right step.

**Comment by rockfordlhotka** [comment]
This will be demonstrated in ProjectTracker, and I don't plan to change the simpler example.
