### ISSUE TITLE
Race condition bug in Csla.Reflection.ServiceProviderMethodInfo.PrepForInvocation

### ISSUE THREAD

**Issue by Eduardo-Micromust** [MarimerLLC/csla#1473]
In Csla.Reflection.ServiceProviderMethodCaller.CallMethodTryAsync a NullReferenceException is thrown if two or more threads reach PrepForInvocation and ServiceProviderMethodInfo is not initialized.
The first thread will mark object as initialized while the properties are still initializing and other thread will get null values for properties not initialized. 
I suggest lock PrepForInvocation while values are initializing to prevent this bug

**Comment by Eduardo-Micromust** [comment]
I think it's better to create a constructor in ServiceProviderMethodInfo receiving the MethodInfo and initialize all properties. It would be easier to use the type and I can´t see any penalty in this change.

**Comment by rockfordlhotka** [comment]
I think the reason I didn't use a ctor is that this type gets used on logical client-side and server-side code.

If it is used on client-side code (logical and physical) then it won't be _invoked_ there, it is just used to find attributes like `RunLocal`. So there's no value in creating and compiling the expression to invoke the method, because that'll never occur.

On the server-side (logical and/or physical) then the expression should be created and compiled, because it will be invoked.

**Comment by rockfordlhotka** [comment]
As a fix though, can't we just move the `bool` value to the bottom of the code block?

In the (relatively rare) case that 2+ threads trigger this code as the app is being initialized it might result in the expression being created/compiled more than once, but that'll be rare and letting it happen is probably cheaper than _always_ using a lock.

Or figure out a way to keep the lock out of the main flow of the code, so any lock occurs only for initialization conflicts, but not over the lifetime of the app.

**Comment by Eduardo-Micromust** [comment]
The way I fixed the code, evaluating the bool before the "lock" and
evaluating again inside the lock, ensures that the lock occurs only in
initialization.



*Eduardo Costa*
  Engenheiro
55 11 2977-7859
eduardo@micromust.com.br
www.micromust.com.br


Em ter., 4 de fev. de 2020 às 17:57, Rockford Lhotka <
notifications@github.com> escreveu:
