### ISSUE TITLE
Some classes use hard coded DataPortal methods names

### ISSUE THREAD

**Issue by Eduardo-Micromust** [MarimerLLC/csla#1477]
Classes using hard coded DataPortal methods names:
- Csla.Server.DataPortalMethodCache;
- Csla.Server.DataPortal;

Hard coded methods names should be used only in .Net 4.0.
"AmbiguousMatchException" is thrown when a method named "DataPortal_Fetch" is marked with FetchAttribute and have injected parameters.

**Comment by rockfordlhotka** [comment]
I'm not sure I understand the problem here. 

Backward compatibility is a requirement - in that all existing code needs to keep running - with the existing `DataPortal_XYZ` names.

Also, it _should_ be possible to keep using `DataPortal_XYZ` with (or without) the operation attributes.

I thought I had tests for all those scenarios?
