### ISSUE TITLE
ApplicationContext lost in Async call to DataPortal_Fetch

### ISSUE THREAD

**Issue by jeffq1958** [MarimerLLC/csla#1538]
**Describe the bug**

**Version and Platform**
CSLA version: 5.1.0
OS: Windows
Platform: WinForms

**Code that Fails**
Provide the failing code, ideally an isolated repro of the issue you are encountering.

**Stack Trace or Exception Detail**
Provide a stack trace, or at least detailed information about the exception.

**Additional context**
I have a large application that is in the process of being upgraded from CSLA 4.6 to CSLA 5.1.  The .NET framework was also upgraded to 4.8.  We are storing some configuration data in the ApplicationContext.GlobalContext.  Once upgraded, if the ApplicationContext.GlobalContext is referred to in a DataPortal_Fetch that is called Asynchonously the ApplicationContext is not available.  Is there some simple way to fix this?  I see lots of posts, but no solution that explains how to fix it.  Any help would be appreciated.

**Comment by rockfordlhotka** [comment]
For certain, `GlobalContext` no longer goes round-trip like it does with a sync call. This is because there's no good way to merge the async result back into the original.

As a result, I strongly recommend against the use of `GlobalContext`, especially for out-of-band info that needs to flow from client to server. You should use `ClientContext` instead, as that flows one-way to the server and doesn't waste the bandwidth coming back from server to client.

You are using `HttpProxy`?

**Comment by JasonBock** [comment]
....cough, cough....create an analyzer that warns people not to use `GlobalContext`....cough, cough.... :)

**Comment by rockfordlhotka** [comment]
Yes, probably a good idea.

`GlobalContext` came into being long, long ago when a very active community member (Peter) was building some pretty cool tracing tool that traced a data portal call round-trip.

When we added async support in .NET 4 it turned out to be unrealistic to merge the copy of `GlobalContext` coming back from the server into the client-side `GlobalContext`. Mostly because multiple server calls could be running at once, and how would you know which won? Total mess.

So really we should be planning to obsolete/remove `GlobalContext` entirely - starting with an analyzer.

**Comment by jeffq1958** [comment]
Thank you.  Will switch to ClientContext

**Comment by rockfordlhotka** [comment]
I'm going to close this issue, as I don't think there's any bug here - just the need (recorded in another issue) to start the process of obsoleting `GlobalContext`.

However, @jeffq1958 - I am providing a tiny WinForms->MVC5 app that shows `ClientContext` flowing from client to server as expected.

[WindowsFormsApp1.zip](https://github.com/MarimerLLC/csla/files/4395375/WindowsFormsApp1.zip)
