### ISSUE TITLE
Err: Csla.Blazor 5.1.0 is not compatible with netcoreapp3.1 Package Csla.Blazor 5.1.0 supports: netstandard2.1

### ISSUE THREAD

**Issue by animjn** [MarimerLLC/csla#1575]
Hi! I receive the following error when building Blazor Server Application referencing Csla.Blazor 5.1.0. Would help greatly if anyone can give any insights into resolving this.

> Csla.Blazor 5.1.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Csla.Blazor 5.1.0 supports: netstandard2.1 (.NETStandard,Version=v2.1)

![Untitled](https://user-images.githubusercontent.com/44891933/79755316-8f11c300-8336-11ea-93fb-9655845ed4c9.png)

**Version and Platform**
CSLA version: 5.1
Platform: Blazor Server Side

**Comment by rockfordlhotka** [comment]
@animjn I am unable to reproduce your issue.

I just created a new SSB project in VS2019 and used VS2019 to add a package reference to Csla.Blazor version 5.1.0. Then I built the project and it works fine.

**Comment by bradtwurst** [comment]
@animjn 

As I've been investigating blazor, it appears that VS will get confused at times.

At times, a full solution clean/rebuild (I know that rebuild is suppose to clean but YMMV) cycle.

Other times, I've had to exit VS all-together and reopen the solution.

about 3/4 of the time, these actions have magically corrected the situations and errors.  The other 1/4 of the time is due to some sort error on my part.
