### ISSUE TITLE
Require initialization of Dependency Injection for use of CSLA .NET

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1738]
The .NET Framework 4.8 and .NET Core (and .NET 5) support the same standard .NET dependency injection subsystem. 

CSLA has used this since CSLA version 3.0, but some of the code in CSLA is rather ugly because we support the DI _and pre-DI_ implementations of various concepts. Starting with version 6 we'll be requiring that a DI service provider be initialized to use CSLA .NET, allowing us to assume it exists within the CSLA implementation.

This is no different from how modern ASP.NET requires initialization of DI, and increasingly people are initializing DI in other hosts such as WPF, WinUI, Xamarin, Blazor, etc.

Using DI to create types means that private constructors for domain business classes is no longer supported. This hasn't been supported when using `MobileFormatter` for many years, and now it is not supported in any scenario.

**Comment by JasonBock** [comment]
I can't say I agree or disagree because I don't exactly get what you mean by this. Does this mean a developer will always have to call `AddCsla()` now when an application "starts up", even if there are no dependencies involved?

**Comment by rockfordlhotka** [comment]
Yes, exactly. That allows the code inside CSLA to stop using `Activator.CreateInstance` in favor of the new DI-based activator that does injection.

It also means we can do things like use DI within CSLA itself to inject things like config or other values throughout the framework.

**Comment by JasonBock** [comment]
Part of me wonders if there's an analyzer in play, but I don't know if it's possible to write an analyzer that says, "hey, you never called `AddCsla()` in your code."

**Comment by ShaiCohen26** [comment]
I _think_ @rockfordlhotka means that if you do not initialize Dependency Injection, CSLA will throw a _runtime_ exception. 

> Starting with version 6 we'll be requiring that a DI service provider be initialized to use CSLA .NET, allowing us to **_assume_** it exists within the CSLA implementation. (emphasis added)

A poor analogy of the new behavior is connection strings. Your codebase assumes the referenced connection string exists; however if the connection string is missing, a runtime exception is thrown.

**Comment by rockfordlhotka** [comment]
Yes, that is exactly what will happen.

It will probably happen early, because I expect the data portal to use DI to configure itself, so the first attempt to call the data portal will result in runtime failure.

**Comment by rockfordlhotka** [comment]
This discussion is valuable to consider when implementing this change: #1983

**Comment by rockfordlhotka** [comment]
In this latest commit I have changed my approach a little.

The massive impact on backward compat (including unit tests) of _requiring_ DI to be initialized might be too much?

For _now_ at least, I've backed off, and if there is no current DI service provider the implementation falls back to using `Activator.CreateInstance` like in the past.

But if there _is a DI provider available_ then all types are now created using the provider, which means any type being created by CSLA (outside of deserialization) should allow DI via constructor.

**This is potentially dangerous** in that someone might store a non-serializable, injected, instance of something in a private field in an otherwise serializable object (like a `BusinessBase` subclass). Of course they'll find out that's a bad idea as soon as they try to use the data portal or otherwise serialize their domain object. Still, I suspect this'll be a new avenue for support issues as people make this mistake.

(the _correct_ solution is to not inject stuff into a domain type; or make sure to always mark the fields storing such injected objects as not serialized)

**Comment by ajohnstone-ks** [comment]
I'm on the fence, so I'll just note everything that comes to mind for me, hopefully that will be helpful.

I think DI support in Csla is as big of a change as moving from business rule methods to full blown classes was in Csla 4.  Moving from 3 to 4, your code instantly didn't compile, and you had to learn how the new rule system works, including things like no mutable state in a BR instance (or static level too).  So I think if there are other large breaking changes like that, it will make that much harder for Csla users to move from 5 to 6.  If the other breaking changes are easier to deal with, even if there are alot, it probably would be fine.

Our experience actually getting injection up an running in Csla though was pretty simple though, but we already had a hand-rolled solution to support injection into server side data portal code & business rule executions, as well as some base classes which most of our tests use.  So it was just a matter of a few lines of configuration, and creating a new Moq for IServiceProvider & duplicating the base configuration already so that `GetService(Type)` matched what we were already doing for various things.  Now as we convert thing to use Inject instead of our custom solution, its just a matter of switching to the IServiceProvider mock in our tests and we're off and going.

What bit me though is not understanding how the scopes were managed (or not) by Csla.  I had made some assumptions, and still all the unit tests passed, and our issue & regression testing all passed.  It wasn't until a few weeks later and our busiest usage period started that I realized they were wrong.  So I think some documentation about how to use DI in Csla, how it is used by Csla, and especially about how scopes are managed should be a requirement before Csla requires DI.  I think that the fact that in an application remote host scenario Csla will not do anything by default to manage scopes should be pointed out as well.  Scoping & lifetime management are really important with DI, so knowing how to Csla works with them is important too.

I'm not sure how many Csla users are doing DI at this point; maybe a lot have their own solutions like we do, maybe not.  For those that aren't an easy button might be good.  Some extension method off of the configuration like `ImNotUsingDISoSetItUpAsNeeded()`  Then later they can do the normal configurations if they want to start using DI.

OTOH, if you're using Csla, your applications is probably complex enough to warrant DI so maybe expecting it is fine.  Plus if you're not, it does bring enough benefit that requiring it now instead of waiting even longer is right.  Requiring business rules to be classes in Csla 4 was a huge breaking change, but I think it forced things to move in a better direction.  Maybe the same can be said for DI, and I think its going to be inevitable.

**Comment by rockfordlhotka** [comment]
Nice summary of the issue @ajohnstone-ks, well said.

Thus far I haven't done any changes that _require_ DI, but I think that'll come yet in CSLA 6. For example, `HttpProxy` could (and should?) rely on DI to get the `HttpClient` instance it needs to work. That would simplify `HttpProxy` because we could remove the current subclass-based configuration scheme and instead rely on a DI-based configuration scheme (as in: I need a special `HttpClient` for some reason, so I create it via DI instead of via a subclass).

**Comment by dazinator** [comment]
@rockfordlhotka in terms of `HttpClient` the prevalent direction of travel is to use [IHttpClientFactory](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0)

I don't advocate CSLA enforcing use of this dependency though. What has worked for me in my own libraries is to allow my library to be configured with a `Func<HttpClient>`

For example, wherever CSLA requires an HttpClient, rather than having an instance injected, obtain the instance from a configurable function call:

```
public class SomeCslaFrameworkCode
{
public SomeCslaFrameworkCode(Func<HttpClient> httpClientFactory)
{


}

public void DoSomething()
{
 var httpClient= httpClientFactory();

}

}
```

If you go this route, then its possible for users that want to use IHttpClientFactory to do so as they can register a function that returns a registered named HttpClient using `IHttpClientFactory` - or for those users that don't use IHttpClientFactory they can create the HttpClient with custom settings with whatever code they like.

Csla can register its own `Func<HttpClient>` as default, so that a user doesn't have to register one, but they can register a custom one if they wish.

If you don't like being dependenct upon a `Func<HttpClient>` you can create your own csla interface like `ICslaHttpClientFactory` that users must implement that returns the HttpClient instance, and again register CSLA's version by default, and this can be injected where needed.

**Comment by dazinator** [comment]
@rockfordlhotka I agree with the approach of not requiring DI, and just activating the type using the IServiceProvider. CSLA just needs to be careful to activate the right types, with the right IServiceProvider (i.e root / default one, vs scoped one). In some situations, you might always want to use one scope or the other depending on the context that the type to be activate is meant to operate within. In other cases it might be fine to use the scoped provider if its available, falling back to the root provider if its not.

**Comment by dazinator** [comment]
Sorry - just changed by responses above several times as normal as my thoughts matured ;-)

**Comment by dazinator** [comment]
- and changed them again.. that's it now I promise ;-)

**Comment by ajohnstone-ks** [comment]
> I don't advocate CSLA (being a framework) enforce that applications use `IHttpClientFactory` though. What has worked for me in my own libraries is to allow them to be flexible enough that the user can provide instances of `HttpClient` from wherever they need to. I typically do this by allowing an a `Func<HttpClient>` to be configured or injected. If my library needs different flavours of HttpClient, then I make this a `Func<string, HttpClient>` where the string identifies the name for the HttpClient being requested. This integrates well with those applications that want to use `IHttpClientFactory` to satisfy that instance, and those applications that don't can create different HttpClient's with different default settings based on that name.

Could this be done by registering the factory method with the container itself, and letting the container call the func?  Then HttpClient could still be the thing injected.  If its Func<HttpClinet>` HttpProxy expects, your Func<string, HttpClient> wouldn't be possible I think.  Just a though.

> I'm not 100% sure that creating the scope should actually be left to the interceptor.

I've been thinking about how supporting injection into the Execute method of business rules might work.   It seems like it might be good to have a scope created when the rule starts executing and disposed at the end; chained rules (and maybe the auth rule that runs before the value is even allowed to be changed?) should use the same scope, and all rules maybe should share a scope when BusinessRules.CheckRules[Async] is called from the BO.  Something unique in Csla explicitly for scope creation/disposable could help with that.  Not that I have any clue how injection into business rules would look though, but your idea could prove helpful there.

**Comment by dazinator** [comment]
> Could this be done by registering the factory method with the container itself, and letting the container call the func? Then HttpClient could still be the thing injected. If its Func` HttpProxy expects, your Func<string, HttpClient> wouldn't be possible I think. Just a though.

The issue you get into is that applications often have more than one HttpClient so registering just one in the container for injection everywhere is often not appropriate.. if you register multiple you need to be able to obtain the right one or atleast have the right one injected into the right services. For example they may have one HttpClient which should be used by service A to talk to api A, and another for service B to talk to api B. You don't register HttpClient in this scenario- you register service A and B, and register them with a factory method that injects the right HttpClient instance. This is what the Http Client Factory "typed services" does: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-5.0#typed-clients but that only works for transient services and that's because the injected httpclient is not meant to be kept for the life of the application. So what if your service is a singleton? Well the thing you can do there is instead of injecting a HttpClient instance you can inject IHttpClientFactory which provides a method to get a httpclient by name. I havent looked at csla code but I was assuming `HttpProxy` was more singleton in nature. If that's the case it should be adapted to obtain a HttpClient via a Func<HttpClient> as it needs it rather than have one instance injected and kept for its entire lifetime. The most flexible way to do this imho is to just allow a `Func<HttpClient>` to be injected. Applications that use IHttpClientFactory can decorate that Func to return a named httpclient that they have configured specifically for csla.

**Comment by rockfordlhotka** [comment]
This is great conversation, but really should be part of its own backlog item, so I created #2025

**Comment by dazinator** [comment]
@rockfordlhotka thanks sorry for the tangent, I dont like to leave questions hanging 👍 - back to this issue..

I agree with using the IServiceProvider where its available and falling back to good old Activator.CreateInstance when its not - this will help preserve some backwards compatibility whilst things are still in flux. I suspect this will be revisited once again if CSLA shifts to an absolute dependency on IServiceProvider. Put it this way - if CSLA chooses to becomes dependent on an IServiceProvider to function and embraces that, then there will always be atleast the root / default IServiceProvider in play and so Activator.CreateInstance should never be necessary, as the alternative can be used that activates the type but allows for DI, makes no sense not to use it...

I do think the new inject attribute for DI into DP methods should require an IServiceProvider though - i can't remember if that is currently the case, i think it might error if there is no IServiceProvider.

Im not sure about this logic: https://github.com/rockfordlhotka/csla/commit/24a0833f91c7bed1176c349ed15826afa5fb4d57#diff-3532e1a3640a39bef1e05242e77be87d67274b2c808bc7264b7a0065cefc5c3dR194

It seems you check for the scoped provider - might want to check the behaviour of that scoped provider property- if there is no current scope IServiceProvider is csla context does it fallback to returning the root / DefaultServiceProvider? Because when activating types you might want to make sure you use the scoped provider if its set, else fallback to the default/ root service provider if that is set, else fallback to Activator.CreateInstance. From the code as written it just looks like it used the scoped or nothing.
