### ISSUE TITLE
Blazor wasm sample and server side code

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#1748]
**Is your feature request related to a problem? Please describe.**

Im just checking something it might not be a problem.
Blazor wasm downloads business objects assemblies to the browser. Its important therefore to keep them lightweight and also not reveal server side logic. The blazor wasm sample shows business object types that currently include the code for server side data portal operations. I havent physically tested the sample, but on a glance of the code, there is no conditional compilation to produce a cut down version of the binaries to be sent to the browser without the server side code - sonething I think silverlight examples used to show.

Saying that, when the linker is enabled (I.e in a release build by default) perhaps it might pick up on some of this code - due to the nature of how the data portal works to locate methods via reflection etc.

I think I would prefer something much more explicit like conditional compilation though, much easier to take direct control over that, than the linker.

**Describe the solution you'd like**

Introduce / define a compilation constant for blazor builds, that will exclude server side methods, and have the blazor wasm sample demonstrate that as a best practice.

**Describe alternatives you've considered**
Letting the linker attempt this work but I think that's probably error prone.

**Additional context**

**Comment by rockfordlhotka** [comment]
I hear you @dazinator. I am not sure just how to solve this issue in an easy way.

We actually disable the linker, and will probably need to continue to do so, because it tends to optimize away code we're invoking dynamically via expression trees. If the linker can't trace a concrete call, it will optimize away important methods.

You _can_ do conditional compilation, but it adds extra projects to the solution. The default is to build one business library as a netstandard 2.0 assembly. But you _could_ build the code twice (like we used to with Silverlight) by having two concrete projects building from a shared project. Nothing stops you from doing that within your solution.
