### ISSUE TITLE
Add code to support compression in the Http data portal channel

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#1881]
The data portal Http channel (HttpProxy and HttpPortalController) should be enhanced to support compression.

These changes shouldn't have an impact unless compression is configured in the web server startup code.

As per https://github.com/MarimerLLC/csla/discussions/1694

**Comment by rockfordlhotka** [comment]
@BlagoCuljak, once you accept the GitHub invite to be a contributor I can assign this issue to you.

**Comment by rfcdejong** [comment]
This new code broke our code at runtime with exception "Specified argument was out of range of valid values. Parameter name: Unhandled CSLA Known type was found"

This is because we override GetHttpClient() to create an own HttpClient pass along the client's AccessToken. 
@rockfordlhotka  Perhaps add a boolean property to add the compression headers or not?

_PS: I find it not very secure that CSLA does not implement this sort of security. If the server is on the internet some man-in-the-middle can capture a request can modify it to post it again and breach security_ 

I was able to fix it:

![image](https://user-images.githubusercontent.com/2665653/106432757-7448af00-646f-11eb-88b3-f1789c1261e4.png)

**Comment by GreatBarrier86** [comment]
For anyone using the sync WebClient, this workaround worked for me.

![image](https://user-images.githubusercontent.com/29482393/107377026-84d4d700-6ab8-11eb-93a7-93b8cdc82560.png)
