### ISSUE TITLE
Private data portal method not found from base classes

### ISSUE THREAD

**Issue by ajohnstone-ks** [MarimerLLC/csla#2287]
**Describe the bug**
There's a bug when Csla looks for a Data portal method to call if the method is defined in a base class.  Previously it worked, but in the most current version an exception is thrown.

**Version and Platform**
CSLA version: 5.4.1 & 5.4.2
OS: Windows
Platform: .Net core & .net framework

**Code that Fails**
```
using System;
using Csla;

namespace ExecuteNotFound {
	class Program {
		static void Main(string[] args)
		{
			Console.WriteLine("Executing command");
			DerivedCommand.ExecuteCommand();
			Console.WriteLine("Done executing");
		}
	}

	[Serializable]
	internal abstract class BaseCommand<T> : CommandBase<T> where T : BaseCommand<T>
	{
		[Execute]
		private void Execute()
		{
			Console.WriteLine("In Execute");
		}
	}

	[Serializable]
	internal sealed class DerivedCommand : BaseCommand<DerivedCommand>
	{
		public static DerivedCommand ExecuteCommand() => DataPortal.Execute(new DerivedCommand());
	}
}
```

**Stack Trace or Exception Detail**
DataPortal.Update failed (Invalid operation - execute not allowed)

```
   at Csla.CommandBase`1.DataPortal_Execute()
   at lambda_method2(Closure , Object , Object[] )
   at Csla.Reflection.ServiceProviderMethodCaller.CallMethodTryAsync(Object obj, ServiceProviderMethodInfo method, Object[] parameters)
   at Csla.Reflection.ServiceProviderMethodCaller.CallMethodTryAsync(Object obj, ServiceProviderMethodInfo method, Object[] parameters)
   at Csla.Reflection.LateBoundObject.CallMethodTryAsyncDI[T](Boolean isSync, Object[] parameters)
   at Csla.Server.DataPortalTarget.InvokeOperationAsync[T](Object criteria, Boolean isSync)
   at Csla.Server.DataPortalTarget.ExecuteAsync(Boolean isSync)
   at Csla.Server.SimpleDataPortal.Execute(DataPortalTarget obj, DataPortalContext context, Boolean isSync)
   at Csla.DataPortal`1.Update(T obj)
   at Csla.DataPortal.Update[T](T obj)
   at Csla.DataPortal.Execute[T](T obj)
   at ExecuteNotFound.DerivedCommand.ExecuteCommand() in c:\tmp\ExecuteNotFound\ExecuteNotFound\Program.cs:line 27
   at ExecuteNotFound.Program.Main(String[] args) in c:\tmp\ExecuteNotFound\ExecuteNotFound\Program.cs:line 9
```

**Additional context**
The sample code works fine in Csla 5.4.0, but doesn't in 5.4.1 or 5.4.2.

**Comment by rockfordlhotka** [comment]
Must be a regression. I thought there was a unit test for this scenario, but I don't see it 😢

https://github.com/MarimerLLC/csla/blob/main/Source/csla.netcore.test/DataPortal/ServiceProviderMethodCallerTests.cs

**Comment by amselem** [comment]
I found the same issue, and suggested a code fix:   https://github.com/MarimerLLC/csla/discussions/2309

**Comment by swegele** [comment]
Noticed what I think is a related issue **ONLY FOR** ReadOnlyListBase<T, C> which broke between 5.3.x to 5.4.2.  
But the wierd thing is the same code below still works fine in ReadOnlyBase<T>

**Background:**
When upgrading to CSLA 5.3.x I added the following to all my readonly base classes which allowed me to get around code analyzer exceptions for having calls to public CTOR.  This technique allowed me to not have to write hundreds of Fetch methods to already existing classes.

`protected static T CslaSafeConstructor()
{
    return DataPortal.Fetch<T>(new BaseOnlyEmptySemaphoreObject());
}

[RunLocal]
[Fetch]
private void Fetch(BaseOnlyEmptySemaphoreObject emptySemaphore)
{
}
`

The point of using private BaseOnlyEmptySemaphoreObject is so I could be absolutely certain that this fetch method in the base class does not and will never step on any public DataPortal_Fetch methods implemented in the real classes.  Then it was a simple text find/replace for CTOR calls to call CslaSafeConstructor() instead.  Maybe that was whacky but it is what I did.

`
[Serializable]
internal struct BaseOnlyEmptySemaphoreObject
{
}`

In CSLA 5.3.x this worked fine for the two readonly base classes (single and list).  Now in 5.4.2 it no longer works for ReadOnlyListBase.  I get exception which is because no corresponding fetch method is found:  
"Invalid operation - fetch not allowed"

StackTrace:

`   at Csla.ReadOnlyListBase`2.DataPortal_Fetch(Object criteria)
   at Csla.Reflection.ServiceProviderMethodCaller.<CallMethodTryAsync>d__11.MoveNext()`

As a workaround on ReadOnlyListBase I removed the parameter and CSLA now finds the method in the base.  

`        protected static T CslaSafeConstructor()
        {
            //fetch because readonly objects do not have a create dataportal implementation
            return DataPortal.Fetch<T>();
        }

        [RunLocal]
        [Fetch]
        private void Fetch()
        {
        }
`

**Comment by amselem** [comment]
Hi

This issue is not totally solved for me in Csla 5.5.0-R21070101

The dataportal calls correctly a private DataPortal_Fetch() in a BusinessBase derived class.   However it fails it there are several DataPortal_Fetch in the inheriting chain classes (System.Reflection.AmbiguousMatchException)

The dataportal call also fails if the DataPortal_Fech belongs to a BusinessBindingListBase derived class  ( 'fetch' operation not allowed )

Both cases work ok in csla 4.6.200.0

**Comment by rockfordlhotka** [comment]
It would be very helpful if you can provide a repro, like a unit test or console app, that shows the issues, thank you!

**Comment by amselem** [comment]
Hi Rocky,

I managed to repro the issues in a modified version of CslaFastStart sample. Let me know if I can further help.

[Csla55_Issues.zip](https://github.com/MarimerLLC/csla/files/6842602/Csla55_Issues.zip)

**Comment by rockfordlhotka** [comment]
Perfect, thank you! I now have failing tests in the unit test suite!

**Comment by amselem** [comment]
Thank you Rocky, all the issues are solved in the latest prerelease!  
When is the final 5.5 version going to be released?

**Comment by rockfordlhotka** [comment]
I was hoping to hear that @amselem!

Given that, 5.5.0 will release within the next few days - probably Monday.
