### ISSUE TITLE
Reduce memory usage of MobileFormatter

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2346]
Right now MobileFormatter creates a flat list of all data fields in all objects in the graph being serialized. Then it writes that flat list to the output stream using a writer.

It might be possible to reduce the memory footprint of serialization and deserialization by just writing all that field data directly, rather than creating the flat array.

The trick with this is that we do need to locate all object _references_ and assign them arbitrary unique key values, so we can't write an _object reference_ to the stream until it has been assigned a unique key value. 

Ideas for making memory usage better include:

* Use source gen
   * Replace serialization of FieldDataManager with source gen
   * Already in the backlog as #2154
* Potentially replace MobileFormatter entirely, serialize/deserialize from stream via reader/writer?
   * Essentially implement all the behavior of MobileFormatter directly into all classes in the graph
   * Trick with this, is abstracting object references to avoid circular reference issues
* Enhance/replace MobileFormatter w/ new SerializationInfo
   * New SI class would write to stream, not use FieldData type at all
   * Trick with this, is abstracting object references to avoid circular reference issues

(notes from conversation with @TheCakeMonster )

**Comment by TheCakeMonster** [comment]
I had a thought on this subject after we discussed it. My realisation was that there's an additional complication with changing SerializationInfo to write directly to a stream, namely what data is available to perform deserialization.

At the moment, we write how many of each type are serialized before writing the collection of them to the underlying stream. This is possible because we do two passes - first to flatten the data being serialized into collections of SerializationInfo, and a second over the collections to write them to the stream. Slimming down the serialization method from the two pass approach to writing immediately in the first pass means we don't know how many of anything we have before we write them. This changes what is possible during deserialization.

I don't think this is insurmountable. Instead of writing how many of items there are in a collection prior to writing all of the items, we could instead write details of what the next single item is before writing it, repeating that for each item. However, this would increase the number of bytes on the wire.

In short, this approach would at best be a trade off. We might be reducing our memory usage a little, but increasing the amount of data sent over the wire.

The current solution is already fairly efficient. It requires newing up an instance of SerializationInfo, plus multiple instances of SerializationInfo.FieldData for each object being serialized. It also boxes value types in the field of type object within SerializationInfo.FieldData. There is some scope for improvements - but maybe not a lot. Trying to avoid the use of FieldData would reduce memory consumption, but there are costs to doing so.

Making FieldData generic, and interacting with it through strongly typed methods is an alternative that might improve performance a little - but does not reduce memory usage. This approach doesn't do away with the type-based switch statements we have in the writers, it just moves them out of the writers. I think the performance improvement only really benefits value types, so it depends on how much of a type to be serialized is made up of value types as to how much of a performance improvement this change may bring.

**Comment by rockfordlhotka** [comment]
We absolutely should avoid increasing the size of the byte stream over the wire - that's the slowest  part of the scenario.

**Comment by rockfordlhotka** [comment]
Not planned.
