### ISSUE TITLE
DeleteSelfChild needs to work with 0 and non-0 parameters

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2396]
#2303 "fixed" DeleteSelfChild so it accepts zero parameters. 

We need to review the CSLA 4 behavior and make a determination about how this should work, as in the DI-based CSLA 5 model it may not be realistic to have the method ignore the UpdateChildren parameter list.

**Comment by rockfordlhotka** [comment]
@michaelcsikos @ProDInfo @JacoJordaan - I will appreciate your help thinking this through relative to what has worked prior to the DI implementation in CSLA 5.

Most notably - why would we _not_ want to have the UpdateChildren parameters flow into the DeleteSelfChild method?

**Comment by ProDInfo** [comment]
I Want to Flow the parameters from UpdateChildren. This work in 5.4.2, but in 5.5.0 only work with 0 parameters, it's a bug. Fail if has parameters like insertchild and updatechild, because only call to 0 parameters method

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by michaelcsikos** [comment]
It used to work with zero parameters since as long as I can remember, which made sense as a child typically knows how to delete itself with no more information required from its parent. However, with an insert, or less often an update, the child needs to know an identifier from its parent which was not known at the time the child was created.

Personally, I would prefer it worked with zero parameters, or with the same parameters as `UpdateChildren`, but it's not a deal breaker if I have to update to the new method. (~250 classes for us.) In theory, everything should be protected by tests. In practice, this can be difficult to achieve when you're doing plug-in development for AutoCAD and Revit. Also, the compiler won't alert us to a mismatch in the parameters.

**Comment by rockfordlhotka** [comment]
I agree with @ProDInfo - it _should_ allow matching parameters like all the other methods. I really wish I'd thought this through more deeply before making the change in #2303. 

Bad Rocky, no cookie! 🍪

I'm trying to remember the original behavior and why it allowed zero parameters as an option. I _think_ it was because (pre-DI) it was easy enough to add a fallback. In fact, I think all methods had a zero param fallback originally.

Now the entire method discovery flow is far more complex, involving a discovery phase, a scoring phase, and (if one score wins) an invocation phase. Whether it is worth trying to special-case this scenario will take some deeper exploration of the code for sure.

**Comment by ProDInfo** [comment]
I agree with @rockfordlhotka. Some times need properties from parent or sqltransaction pass from parent to children to delete on the same unit of work.

A suggestion but I don't know if this it's very complex or not. First of all try to match like UpdateChildren and if not found method, fallback to zero parameters. For me I don't need zero parameters, just match Insert or Update child. But If @michaelcsikos  need it, it can be a solution that works for both.

**Comment by michaelcsikos** [comment]
If I can't have a zero parameter version, that's OK. There's already a lot of breaking changes I need to fix in the move from 4.11.2 to 5.5, so this will just get added to the list. At least these are easy to find with a simple text search. This may catch some other people out, but they'll be able to find our conversation. When I first reported it, no one had mentioned it here on the forum.

**Comment by rockfordlhotka** [comment]
I believe I have the best of both worlds implemented in this PR: https://github.com/MarimerLLC/csla/pull/2401

If a method can't be found with matching parameters, the code (only for DeleteSelf and DeleteSelfChild) attempts to find a zero parameter method to invoke.

Frankly this feels a little dirty, but it does preserve backward compatibility.

**Comment by ValentijnMakkenze** [comment]
We just upgraded from version 4.11.2 to 5.5.0 and lots of tests are failing because the wrong Child_DeleteSelf method is called.

  protected void Child_DeleteSelf()
  protected void Child_DeleteSelf(object parent)

In version 4 the delete with parent parameter was called but now the delete without arguments is called.
In the 5.5.1. version the correct method is called again.

Any indication when 5.5.1 will be released?
