### ISSUE TITLE
Remove the context/connection manager types from Csla.Data

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2633]
These types are no longer required, because database contexts, connections, and transactions can be managed via dependency injection.

OR we could consider changing these types to be DI-friendly, and maybe have them still provide value within the context of dependency injection:

* Stop reference counting (they'd be a singleton)
* Have them work more like `IHttpClientFactory`, where they get injected and then provide a named instance of the manager type

**Comment by TheCakeMonster** [comment]
I think there is still a need for something very similar to ConnectionManager, as discussed via Discord.

In this comment, I'm only talking about ADO.NET data access using an IDbConnection.

For saving an object graph, we need to use the same connection for all of the objects in the graph - perhaps for the lifetime of a server-side dataportal operation. If we don't do that, we risk accidentally triggering promotion to a distributed transaction, which is an unnecessary expense for access to a single database. However, there is a subtlety - it's reuse of the same connection _per database_. 

It is possible that you would need to access different databases within the same object graph, so some subset of people may need to be able to request a named connection in some way, to cater for that scenario. In this more advanced scenario you do have to deal with distributed transactions, if TransactionScope is in use - but it's still a valid scenario that people may need to be able to manage.

The need to manage a connection across data access operations in multiple classes is why ConnectionManager was created - and to me it feels like that need remains. I don't think that the need is entirely negated by the existence of DI - not when considering operations on an object graph, rather than just a solitary root object.

I don't use EF very much, so I'm not entirely confident I can imagine whether the same applies to this more common usage pattern. However, I do wonder whether exactly the same problem exists for ORMs as well.

**Comment by rockfordlhotka** [comment]
I an not convinced these types are necessary.

In your code you can register your database types like this:

```c#
builder.Services.AddScoped<IConnection1>(
  (provider) => new Microsoft.Data.SqlClient.SqlConnection(connectionString1));
builder.Services.AddScoped<IConnection2>(
  (provider) => new Microsoft.Data.SqlClient.SqlConnection(connectionString2));
```

And you just need to define those two connection interfaces:

```c#
  public interface IConnection1 : IDbConnection { }
  public interface IConnection2 : IDbConnection { }
```

Then in your code, when you need a connection, you just request `IDbConnection1` or 2 depending on your needs.

**Comment by TheCakeMonster** [comment]
OK, I see. And because it's registered as Scoped, and under the covers the framework creates a new scope for each server-side DataPortal operation, if requested using the [Inject] attribute in a data access method, the lifetime of the connection would automatically be the lifetime of the main/top-level DataPortal operation?

I think maybe that was the bit I was missing. If that's true that the lifetime would be managed correctly - scoped to apply to the object graph's data operation as a whole, then I see your point about it having become redundant.

**Comment by rockfordlhotka** [comment]
I've decided to leave these types in the framework for now.

I do not think they have value in the modern DI-based world, but I suspect a lot of people have legacy codebases that use them. It does no harm to leave them for legacy users.

**Comment by rockfordlhotka** [comment]
Actually, I'm going to leave them, but mark them as obsolete.
