### ISSUE TITLE
LocalProxy should use a consistent app context type

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2775]
Now that we are past all that, I see two issues related to the `Csla.AspNetCore.ApplicationContextManager`:

1.  During a HostedService instantiation of business layer, the code errantly selects the `ApplicationContextManagerHttpContext` which simply throws a NULL error for httpcontext.  This is because a HostedService call happens with no circuit and no httpcontext.  IMO in that scenario the code should select the `ApplicationContextManagerBlazor.`  This works great if you edit as follows:

```cs
if (activeCircuitState.CircuitExists || httpContextAccessor.HttpContext is null)
{
  ActiveContextManager = (IContextManager)ActivatorUtilities.CreateInstance(provider, typeof(ApplicationContextManagerBlazor));
}
else
{
  ActiveContextManager = (IContextManager)ActivatorUtilities.CreateInstance(provider, typeof(ApplicationContextManagerHttpContext));
}
```

2. Now, for a normal instantiation of a business layer call (which is inside a circuit), I noticed this constructor gets called twice.  The first time , from injection on a BSS razor page/component, it is called and the CircuitExists property is true so I get an instance of `ApplicationContextManagerBlazor` as expected.  
But then on logical server side of the dataportal this gets called again because of the new scope created.  This time CircuitExists property is false, so I get an instance of `ApplicationContextManagerHttpContext`.  That seems wrong to get one on client side of dataportal and a different one on logical server side.  I'm using LocalProxy of course for my testing.

_Originally posted by @swegele in https://github.com/MarimerLLC/csla/issues/2773#issuecomment-1039934424_

**Comment by rockfordlhotka** [comment]
@swegele it seems to me like we need to cover three scenarios.

1. There is an active circuit, so use the Blazor context manager
2. There is not an active circuit, but there is HttpContext, so use the HttpContext context manager
3. There is no circuit and no HttpContext, so use a private field context manager

**Comment by swegele** [comment]
Regarding #1 - (left a comment on original thread) the AuthenticationStateProvider is indeed available and is of the correct type `Microsoft.AspNetCore.Components.Server.ServerAuthenticationStateProvider`.  So we _may not_ need a 3rd type?

Regarding #2 - I've no idea what to suggest to get DI to give the correct ApplicationContextManager before and after the dataportal call when using the LocalProxy.

**Comment by swegele** [comment]
Transferring discussion here from #2773 - about the Issue number 2 above:  Perhaps this issue should be retitled as it looks like we don't need a third context manager type to make HostedService work.

The only remaining concern I have is that in a normal BSS-only call to the business layer, using LocalPortal, the following behavior happens:
1.  Upon client side instantiation of business layer, the `Csla.AspNetCore.ApplicationContextManager` detects that `activeCircuitState.CircuitExists = true` and thus it selects `ApplicationContextManagerBlazor` as the IContextManager

2. DataPortal is called.  On the logical server side of local DataPortal, by default a new scope is created (if the option is set to true)  

3. Because of the new scope, `activeCircuitState.CircuitExists` is now false

4. Thus the `Csla.AspNetCore.ApplicationContextManager` now selects `ApplicationContextManagerHttpContext` as the IContextManager

This should not be, because in the context of BSS, Microsoft discourages the use of HttpContext as @TheCakeMonster discovered and reported (which caused the creation of the hybrid ApplicationContextManager.  The current mechanism to test for BSS does not work on the server side of the local dataportal.

Possible solutions:

(not so good)
1. Disable the new scope being created by default on the logical server side.  (I don't know what the consequences of this is because I don't yet understand why that feature was added and defaulted to true).

(better?)
2. Prior to entering the DataPortal, in some appropriate spot, add a flag to the ClientContext that crosses the portal and alerts the logical server side that this call has come from a BSS client.  Thus that code can then properly select the `ApplicationContextManagerBlazor` as the IContextManager.

**Comment by TheCakeMonster** [comment]
I'm thinking more and more that I've accidentally led us down the wrong path with the question I raised in issue #2702. I asked the question of whether the context manager created by LocalProxy should be created using DI; I now realise the answer to that was no, not really.

We have accidentally placed an unwritten expectation upon our context manager implementations: that they can provide multiple, separate backing stores for context data. We assume that we can create a new instance of the context manager and have it hold an entirely separate, disconnected set of state for use inside of LocalProxy. In a number of cases, that isn't true - it's an inappropriate expectation.

In both the HttpContext and Blazor Scoped context managers (and others) there is only one backing store. The assumption that we can create a separate copy is invalid.

I believe we should revert part of the fix to #2702; I think using a single, known context manager within LocalProxy is the right approach - the one we were using before, using thread-local storage. The only change we need to make from the original code prior to that PR is to fix the fact that the clone of the context information was incomplete - that was the bug, not the use of a different context manager.

**Comment by swegele** [comment]
@TheCakeMonster I believe you've put your finger on the little sneaky issue that was causing me so much grief...I really struggled last night till (unpublished early morning hours) trying to get my PR that showed an example that "worked".  I constantly felt like I needed BOTH the chicken and the egg at the same time.  My brain was hurting.

Our dev team and the POC BSS app I've been working on is just about ready to start using CSLA 6 (I was hoping next week-ish).  So I'm hoping, nay I'm begging the revert doesn't take too long.  Should @rockfordlhotka agree on this, then please consider me available to help do some testing (or whatever is needed) when a PR is up.

**Comment by swegele** [comment]
@rockfordlhotka Any more thoughts in your evaluation of whether to revert as suggested by @TheCakeMonster?

I'm willing to help if I can.

**Comment by rockfordlhotka** [comment]
@swegele I've been on vacation, coming back online tomorrow, when I plan to catch up with the extensive conversations.

**Comment by rockfordlhotka** [comment]
Hmm. I am a bit lost, and so will try to summarize.

1. We do have a real issue where the Blazor context manager should be used `if (activeCircuitState.CircuitExists || httpContextAccessor.HttpContext is null)` (resolved in PR #2773)
2. There is an issue where an aspnetcore host that runs SSB and aspnetcore both can't properly be configured to dynamically set the flag so LocalProxy does/doesn't create a DI scope (now tracked in #2793)
3. It _may_ be the case that LocalProxy (when creating a new DI scope) should use a simple self-contained application context manager (storing context and user values in AsyncLocal fields)

_This_ issue would track the third point here - which is to resolve what context manager should be used in a LocalProxy-created DI scope.

**Comment by swegele** [comment]
Yes I believe that summarizes the issues in play (that I know of).  

1.  Pretty simple fix 
2.  I think your right...a quick check with a service to know whether to create a new scope should do it
3.  If LocalProxy always creates the same "simple self-contained" app context, then many things get easier (based on my testing).  Regardless of new scope or not...the same app context is used.  Nice and easy.

**Comment by rockfordlhotka** [comment]
LocalProxy now creates a (new) consistent type of application context manager. This implementation maintains all values (including the current user) in AsyncLocal fields, and so is isolated from anything else that might be going on in the app.

**Comment by swegele** [comment]
Wow that was fast!  Everything looks good except this one change isn't included yet (unless I missed it) in the `Csla.AspNetCore.ApplicationContextManager` to keep a HostedService in a BSS app from blowing up immediately looking for HttpContext.

`if (activeCircuitState.CircuitExists || httpContextAccessor.HttpContext is null)`

As soon as that's in, I will fetch/pull and start testing everything in my POC and I'll report findings.
