### ISSUE TITLE
Problem with how OnPropertyChanged fires for WinForms app vs Xamarin app

### ISSUE THREAD

**Issue by GreatBarrier86** [MarimerLLC/csla#2872]
I've run into a problem with `OnPropertyChanged`. In WinForms, it appears `OnPropertyChanged` only fires for the property that is actually changing even though `BusinessRules` are run for any of the dependencies. In XAML, `OnPropertyChanged` fires for the dependencies as well. I do know this relates to the `ApplicationContext.PropertyChangedMode` property.  

Because of this, I'm running into inconsistent behavior between our WinForms app and XAML app. Certain methods are getting called in `OnPropertyChanged` that we only expect to get called when that property value actually changes and not when it's "Changed" as a dependency, like the attached image. I tried setting `PropertyChangedMode` to `Windows` for the XAML app, but certain validation isn't being shown in the UI like it is when set to `XAML`

Do you have a suggestion on how to handle this?

![image](https://user-images.githubusercontent.com/29482393/161560684-2dc1fce9-4544-486c-925a-f97d506078aa.png)

**Comment by hurcane** [comment]
I don't think there is an ideal solution to this discrepancy. You can change the Winforms configuration to behave like the WPF app and raise an event for every property that was changed. The downside to this is a potential performance issue because Winforms databinding reads every bound property when a single property changes.

We have chosen to live with the performance hit, which is not usually noticeable. When it is noticeable due to a property that is somewhat complex to evaluate, we add an internal field to store a "cached" result, often using a nullable value. On any property change that could affect the cached result, we clear the cached field and the first property get will calculate it, but subsequent property gets will just return the cached result.

**Comment by GreatBarrier86** [comment]
I'm trying to understand what you're saying. It seems to me like for XAML, if we change Property X, and there is a dependency between Property X and Property Y, OnPropertyChanged will fire for BOTH. Am i correct in that assumption?

**Comment by rockfordlhotka** [comment]
We (you and I) don't control `INotifyPropertyChanged` - this interface is defined by Microsoft for data binding.

CSLA implements this interface specifically for the purpose of supporting data binding, nothing else. Any other use of the `PropertyChanged` event "isn't supported" - or at least it is only supported if you live within the boundaries of what data binding expects.

Unfortunately Microsoft hasn't been consistent with their use of `PropertyChanged` events. 

* Windows Forms refreshes the entire UI (all bindings) for _every_ `PropertyChanged` event it receives.
* The way I've been using Blazor also triggers an entire UI refresh of bindings for _every_ `PropertyChanged` event.
* WPF, UWP, and Xamarin are the opposite, where they refresh _only_ the binding for the property name specified in the `PropertyChanged` event.

CSLA has a `PropertyChangedMode` configuration setting that toggles between working for Windows Forms or WPF.

If you are building a WPF/UWP/Xamarin app you _must_ use that mode, or your UI won't refresh correctly. In that mode lots of `PropertyChanged` events are raised, because we need one for each changed property. If you use this mode in Windows Forms it will _work_, but the UI will refresh all the data bindings _a lot_, which can be inefficient or even cause UI flicker on large data entry forms.

If you are building a Windows Forms app you can use either mode - but again, there's a cost to using the WPF mode because that's not now Windows Forms is designed.

**Comment by GreatBarrier86** [comment]
Sorry I'm behind, but I'm trying to understand. Basically you're raising it for the dependent properties because XAML's `IPropertyChanged` implementation isn't doing it, right?

It sounds like from a design-perspective (.NET-wise, not you), there is not a great way to handle this situation when the business objects are used for both WinForms and XAML. It seems that the "best" option would be to use XAML mode for WinForms and perhaps implement something like @hurcane suggested.

**Comment by rockfordlhotka** [comment]
Close 😀

Microsoft implemented data binding differently in XAML from Windows Forms. In XAML, they require a `PropertyChanged` event for every property that changes, because they only refresh _one binding_ based on the property name provided via the `PropertyChanged` event. In Windows Forms they (imo) did it wrong, and they refresh _all bindings_ for every `PropertyChanged` event, ignoring the property name provided by the event.

So back in the early 2000's, before XAML, I implemented CSLA to minimize the number of `PropertyChanged` events that were raised, trying to only raise _one_ event for a whole batch of property changes. This made Windows Forms work well.

Then in 2005-2006 (??) when WPF came out I had to figure out how to make CSLA work with WPF (which wants one `PropertyChanged` event for each changed property) without crippling performance of Windows Forms apps, which refresh the entire UI for each event. To solve this, the `PropertyChangedMode` configuration switch was added to CSLA, and it _defaults_ to the right setting depending on whether your app is Windows Forms or WPF.

If you use the `PropertyChanged` event for something other than data binding, then you need to understand all these gory details, because yes, the behavior of how the event is raised is different between Windows Forms (and now Blazor) and XAML-based UI's.

You absolutely _can_ always use the XAML mode (override the default `PropertyChangedMode` when necessary), keeping in mind that there might be performance or flickering issues in Windows Forms/Blazor UIs.

**Comment by GreatBarrier86** [comment]
So let me ask this. What is the proper reason to use `BusinessBase.OnPropertyChanged`? In a PERFECT world, would it be used to call functions to set other properties. Imagine a scenario where setting `OnPropertyChanged` for Property X calls a calculation function that sets a value for Property Y. Should that be done there? Or should that calculation set be done in in a `BusinessRule` using `Context.AddOutValue`?

**Comment by rockfordlhotka** [comment]
Ideally all business rules are implemented as business rules. Thanks to @jonnybee, the rules engine is quite robust and should meet most needs.

**Comment by GreatBarrier86** [comment]
Then what would be the idea use of OnPropertyChanged on the BO side? Just trying to learn how it should be used.

**Comment by hurcane** [comment]
I concur with Rocky. We have projects using Csla 3 and Csla 5. In Csla 3, we commonly used PropertyHasChanged() or OnPropertyChanged() and also event handlers within the business objects that handled the PropertyChanged event from INotifyPropertyChanged.

With Csla 5, we have always been able to process internal side effects using business rules and overriding OnChildChanged when child object changes need to trigger a rule evaluation in a parent class..

**Comment by GreatBarrier86** [comment]
@hurcane, just so i'm clear, if you had to do a calculation routine to set Property Y when Property X changes, you would use a `BusinessRule` and `AddOutValue`? Or would you set the Property directly using `Context.Target.PropertyY = CalculatedValue`?

**Comment by hurcane** [comment]
We always use AddOutValue. We never change properties through context.Target.

**Comment by GreatBarrier86** [comment]
Does AddOutValue cause OnPropertyChanged to fire for it after the value changes or not? Is that what using AffectedProperties is for?

For some context, when we upgraded from CSLA 3 to 5, we didn't fully accommodate the new design necessary for setting properties in business rules.

**Comment by GreatBarrier86** [comment]
I understand that.  I was wondering if AddOutValue bypassed notifying property changed. It sounds like it does not.
