### ISSUE TITLE
Rework ApplicationContext to maintain state in ExecutionContext (or similar)

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#29]
Instead of using TLS and/or HttpContext.Current, ApplicationContext could store its context in the LogicalContext value of ExecutionContext. The .NET framework flows a copy of ExecutionContext onto each thread used as part of the app's logical process flow.

The drawback to this is that ExecutionContext probably doesn't exist on WinRT.

An alternate solution would be to create a dictionary keyed using weak references to Thread and have ApplicationContext lazily copy the master context to a new entry in this dictionary when a new thread is used. This seems complex, but might provide a common implementation across all platforms.

**Comment by oatsoda** [comment]
This would be very useful - at the moment when ExecutionLocation = Server the ApplicationContext.ClientContext is only stored at a thread level so any multithreading on a physical server tier requires you to manage this ClientContext state yourself for new threads.

Equally could you make a case for the ClientContext to only be AppDomain wide when LogicalExecutionLocation is Client? (http://forums.lhotka.net/forums/p/116/922.aspx)

**Comment by rockfordlhotka** [comment]
This wouldn't change that behavior - ExecutionContext is generally per-thread, but I'm told that it is a more generally available solution than TLS.

Also, if you build a web app the code running on the web server has execution location of Client, because the web server is the "client" - with the assumption that you may call an app server that would be "server".

AppDomain-wide values in a web server obviously leak data across all users of the web server.

**Comment by oatsoda** [comment]
Yes, as I understand ExecutionContext exists on the current thread and is then [copied to any child threads created](http://blogs.msdn.com/b/pfxteam/archive/2012/06/15/executioncontext-vs-synchronizationcontext.aspx).

This is what I am having to fix up at the moment - for 2-Tier setups the ClientContext on ExecLoc=Server is TLS so exists only on the current thread and I have to copy it to any child threads.  But then when I run in 1-Tier setup I have to manage the fact that the ClientContext when ExecLoc=Client is at the AppDomain level....

Are you therefore saying that ClientContext becomes AppDomain-wide when you host on a web server? What conditions cause the server-side ExecutionLocation to be set as Client?

**Comment by jonnybee** [comment]
@oatsoda CSLA has a BackgroundWorker and TaskScheduler that will pass context and culture to the background thread. Have you looked at these?

**Comment by oatsoda** [comment]
@jonnybee Yes, I have.  But surely it doesn't help ClientContext in an n-tier setup where ClientContext is set on the AppDomain...

**Comment by oatsoda** [comment]
What I am looking to do is add a dependency to my AuthorizeDataPortal which processes the "Client  Context", e.g.

    public interface IClientRequestContextHandler 
    {
        void HandleClientContext();
    }

The AuthoriseDataPortal will just call this method before carrying out authentication/authorisation.

For 1-tier I am going to be using ExecutionContext on the client-side instead of ApplicationContext.ClientContext (this is because I have 1-tier applications which are multi-tenanted), so the concrete implementation of the above will do nothing as the ExecutionContext will have been set on the client.

For 2-tier+ I will create an implementation of the above which takes values out of the ApplicationContext.ClientContext and puts them onto the ExecutionContext `CallContext.LogicalSetData`

This way all of my server-side code can be assured of having the context set correctly (I actually have another abstraction which will pull the data out of the ExecutionContext for consuming classes).

**Comment by rockfordlhotka** [comment]
"client" doesn't mean client workstation - it means whatever location is running the UI code. In a web app scenario the web server is running the UI code, so it is "client".

**Comment by rockfordlhotka** [comment]
The `Csla.ApplicationContext` values being at the AppDomain level on *some* client platforms is due to the sad reality that some client platforms don't allow access to TLS (WinRT/UWP/WP/SL).

**Comment by rockfordlhotka** [comment]
This 'mis-use' of AppDomain to store context is the reason this issue exists actually - notice the last para in the OP about an alternative approach using a list of ApplicationContext instances indexed by thread number. The point of that is to provide per-thread isolation (so to speak) of ApplicationContext for platforms where TLS and HttpContext aren't available.

**Comment by oatsoda** [comment]
OK, so looks like this issue doesn't necessarily cover what I am having problems with at the moment.  However, broadly speaking, I think both this and my issue are about making it more consistent - mine being making it more consistent between different Tier configurations - this being making it more consistent between different application technologies.

> "client" doesn't mean client workstation - it means whatever location is running the UI code. In a web app scenario the web server is running the UI code, so it is "client".

But a web server could just be hosting the CSLA SOAP service rather than a web app - so I was wondering by what criteria CSLA would decide the ExectutionContext was client?

**Comment by jonnybee** [comment]
In that case the "serverside" soap interface is considered a client. 

It is the serverside DataPortal implementation that sets ExecutionContext to Server. So assuming that you have SOAP interface implementation on top of your CSLA business objects then the SOAP interface is considered a "client".

**Comment by oatsoda** [comment]
Ok, thanks - was hoping someone would say that :)

**Comment by rockfordlhotka** [comment]
Now being tracked and resolved in #729
