### ISSUE TITLE
Blazor no longer requires text-based serialization

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#2922]
In the current code, the `HttpProxy` supports wrapping the serialization byte stream into Base64 text, because Blazor didn't support passing a binary stream over http. That may no longer be true, and if the limitation has been removed from Blazor, then the entire `UseTextSerialization` concept in the HTTP data portal channel should be removed.

**Comment by danielmartind** [comment]
Is it needed for Xamarin?

**Comment by TheCakeMonster** [comment]
I wonder whether we might regret removing this, as there might be another new client in the future that suffers the same limitation. If it isn't expensive to support this feature then maybe we should leave it in?

The fluent `AddBlazorWebAssembly()` method sets the associated value by default, so that would need to be changed. Changing this would of course be a breaking change, as removing it from `AddBlazorWebAssembly()` would change the behaviour of the client, but the setting also needs to be changed on the remote end at the same time, or DP calls fail.

A couple of references to the change to Blazor WASM's ability to support binary data, from Steve Sanderson:
https://github.com/dotnet/aspnetcore/issues/12685#issuecomment-916151555 
https://github.com/dotnet/aspnetcore/issues/16257#issuecomment-391280161

Change was committed in
https://github.com/dotnet/blazor/pull/815

**Comment by rockfordlhotka** [comment]
I agree that it shouldn't be removed, and changing the default would be a breaking change (hence is a CSLA 7 thing).

But making it easier to change the setting, or at least _recommending_ changing the setting for CSLA 6 makes sense I think.

**Comment by rockfordlhotka** [comment]
This **IS** a breaking change.

I moved the static `UseTextSerialization` property in `HttpProxy` into `HttpProxyOptions`, so text serialization is still an option, but is no longer the default for Blazor wasm.

This means that _server controllers_ that support Blazor need to be altered to no longer set the protected `UseTextSerialization` property to `true` _or_ the Blazor wasm client needs to explicitly indicate that text serialization should be used.

Because text serialization doubles the size of data over the wire, the recommended solution is to update the server controller code.

**Comment by rockfordlhotka** [comment]
Oops - that last commit was for #2972
