### ISSUE TITLE
Support the Xamarin Unified API

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#312]
http://blog.xamarin.com/unified-api-and-64-bit-support-complete/

**Comment by rockfordlhotka** [comment]
@Bowman74 - the priority on this turns out to be higher than I expected, as neither the Android nor iOS solutions can fully build (Android does w/ warnings I guess, but iOS is total fail) at this point.

**Comment by Bowman74** [comment]
OK, there is now a pull request.  Congratulations we now also have support for OSX.  This will create a new nuget package as we now support the 32 bit classic iOS API and the new 64 bit unified API.

At some point we may want to phase out support for the classic API but for now we should probably keep them both since there are not really any code differences except a few using statements.

**Comment by Bowman74** [comment]
You will also want to be on the Xamarin beta channel to build.  It was supposed to be moved to the stable channel yesterday but for some reason it was delayed.
