### ISSUE TITLE
Implement parameter overloads for sync data portal Execute methods

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#3237]
https://github.com/MarimerLLC/csla/issues/1775 adds the ability to pass parameters to `ExecuteAsync`. This needs to be added to the sync `Execute` methods as well.

**Comment by mtavares628** [comment]
@rockfordlhotka Is there any ETA for this?  With it being an oversight from the last release, I was hoping that it would be added to a service release.  I only ask, because as I convert my project to CSLA 6,  I would like to convert my Commands to this new methodology for both sync and async, but because sync isn't there yet, I've been having to stick with the old methodology.

**Comment by rockfordlhotka** [comment]
I am working on it currently. It isn't easy to implement.

**Comment by mtavares628** [comment]
No worries. My apologies. I didn't realize the the level of effort for it.  I thought it may have just been an oversight in terms of checking in the code when you had completed it for the async version.  Thanks for putting in the time.

**Comment by rockfordlhotka** [comment]
I want to do it right, and that is turning out to be more work than expected.

**Comment by mtavares628** [comment]
@rockfordlhotka no worries.  I just saw that you bumped #1707 to v8 and that this issue has also been removed from v7.  Will this also be bumped to v8 or is this more of a v7.0.1 issue?

**Comment by rockfordlhotka** [comment]
Ha! You literally caught me mid-planning as I move things around 😳

Yes, I expect this is a 7.1.0 thing - I just need to get 7.0.0 moving - for my own sanity if nothing else.
