### ISSUE TITLE
Can Modify the ViewModelBase

### ISSUE THREAD

**Issue by JavierJJJ** [MarimerLLC/csla#335]
I want when I changed the model in a viewmodel raise a event. In your code have a event but only in NETFX_CORE.

Can you change the instruction for execute on all systems: WPF, Silverlight, ...?
viewmodel.OnPropertyChanged("Model");

Thanks.

#if __ANDROID__ || __IOS__
    public object ModelProperty;
#else
    public static readonly DependencyProperty ModelProperty =
        DependencyProperty.Register("Model", typeof(T), typeof(ViewModelBase<T>),
#endif
#if NETFX_CORE
        new PropertyMetadata(default(T), (o, e) =>
#elif __ANDROID__ || __IOS__
#else
        new PropertyMetadata((o, e) =>
#endif
#if !__ANDROID__ && !__IOS__
        {
          var viewmodel = (ViewModelBase<T>)o;
          if (viewmodel.ManageObjectLifetime)
          {
            var undo = e.NewValue as Csla.Core.ISupportUndo;
            if (undo != null)
              undo.BeginEdit();
          }
          viewmodel.OnModelChanged((T)e.OldValue, (T)e.NewValue);
#endif
#if NETFX_CORE
         <b>viewmodel.OnPropertyChanged("Model");</b>
#endif
#if !__ANDROID__ && !__IOS__
  }));
#endif
</code>

**Comment by rockfordlhotka** [comment]
In most cases ViewModelBase is a subclass of DependencyObject, and DependencyObject automatically raises a PropertyChanged event when the Model property is changed because the Model property is a DependencyProperty.

Android and iOS don't have that concept, and if I remember correctly WinRT doesn't automatically raise the event like it should.

**Comment by rockfordlhotka** [comment]
Do you have a test showing that the event isn't raised in a scenario where it should be raised?
