### ISSUE TITLE
Allow instance of IAuthorizeDataPortal to be set programatically

### ISSUE THREAD

**Issue by oatsoda** [MarimerLLC/csla#366]
Currently if you want to specify a custom IAuthorizeDataPortal you can only specify this in a config file using the "CslaAuthorizationProvider" app setting.

It would be very helpful to be able to specify this in code (much like the DataPortalActivator) so that this dependency can be injected.

It would also be beneficial if there were some way that the instance you provide is used for all IAuthorizeDataPortal calls, rather than creating a new one per-call, so that any dependencies do not require re-resolving each time.

**Comment by rockfordlhotka** [comment]
The challenge with setting this via code is that no user code runs prior to the IAuthorizeDataPortal call. That call is the first time the server-side data portal invokes any user code on the server.

So to set this value via code you'd need to load some *other* user code via config file to do per-call initialization of the server-side data portal. I'm not sure I see the value in adding such a feature?

**Comment by oatsoda** [comment]
The value would be that **I** can control the dependencies and lifetimes of the instances of IAuthorizeDataPortal.  

It would be nice if perhaps Csla used an abstract factory to get instances of the various optional components (e.g. IAuthorizeDataPortal, IDataPortalActivator) rather than having to specify them separately (IDataPortalActivator I have to create and assign in code, IAuthorizeDataPortal I have to specify in the config file). 

    public interface ICslaComponentFactory
    {
        bool CreateAuthorizeDataPortal(out IAuthorizeDataPortal concrete);
        bool CreateDataPortalActivator(out IDataPortalActivator concrete);
        ///... etc.
    }

That means I can then control any dependencies that the IAuthorizeDataPortal or IDataPortalActivator might have, and also I can control their lifetimes so that every call doesn't have to keep creating new instances.  I can also set up everything through my usual DI container.

**Comment by rockfordlhotka** [comment]
Keep in mind that the server is stateless. This means that each client request coming into the server starts fresh with nothing special.

There needs to be some mechanism for you to load your custom code - for the data portal to know what custom code you want to load. That _very first_ bit of code must be loaded via config file because you don't have any code running yet that can tell the data portal what to load.

After that first bit of code has been loaded via config, you can set up an IoC container and do what you'd like throughout the remainder of the client request.

**Comment by oatsoda** [comment]
I guess if you are running on IIS then that is true, but if you are using ServiceHost then the process is fixed and state can exist (only if you want it to).

I don't want to have my IoC container passed around into an IAuthorizeDataPortal, I want to have a single Composition Root so that I can resolve what I need and dispose it.  If Csla had a single abstract factory like above, I could specify *just this* in the config file (for Csla to create) and this becomes my Root and then all components (e.g. IAuthorizeDataPortal, IDataPortalActivator) can be requested by Csla from there.  I am then free to use my IoC container as I please.

**Comment by rockfordlhotka** [comment]
I surely hope each request is stateless (even if the host process is persistent), otherwise bad things will happen because state will 'leak' across users.

I'm quite certain that regardless of _which_ host technology you use, ASP.NET ensures each client request is stateless and isolated.

**Comment by rockfordlhotka** [comment]
I'm going to close this issue, primarily because I believe there _is_ a workaround for you.

The _very_ first code that runs on the server for handling each data portal request is the data portal host code (such as `WcfPortal`, `HttpPortal`, etc.).

The host is responsible for 

1. accepting the byte stream from the client
1. deserializing the byte stream into an object graph
1. creating an instance of `Csla.Server.DataPortal`
1. invoking the server-side data portal to do its work

There is already a constructor for the server-side data portal that allows you to pass in the `IAuthorizeDataPortal` (or at least the type).

So if you want to run code _before_ `IAuthorizeDataPortal` is invoked - to initialize your IoC container for example - then you can create your own custom subclass of `WcfPortal` or `HttpPortal`.

Of course _that_ type must be defined in the web.config file.

**Comment by oatsoda** [comment]
@rockfordlhotka Thanks Rocky for the update; I will take a look at what you suggest. Much appreciated!
