### ISSUE TITLE
Remove hard-coded use of MobileFormatter

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#3748]
There are a number of places where I've been lazy and directly used MobileFormatter rather than getting the formatter via configuration. Those should be fixed.

**Comment by kcabral817** [comment]
Lazy,  oh my god??? Not a word I would use to describe your effort, dedication, and results.  I for one am thankful you have stayed the course.

Have a nice day.

Kevin



________________________________
From: Rockford Lhotka ***@***.***>
Sent: Monday, March 25, 2024 8:27 PM
To: MarimerLLC/csla ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MarimerLLC/csla] Remove hard-coded use of MobileFormatter (Issue #3748)


There are a number of places where I've been lazy and directly used MobileFormatter rather than getting the formatter via configuration. Those should be fixed.
