### ISSUE TITLE
Analyzer: Constructor checks

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#391]
I think I can add two analyzers for constructors (or at least try :)) 

The first one is to ensure a BO has a public constructor. This would be an error if it didn't.

The other one is that a BO should probably not have any other constructors other than the public, no-arg constructor. If a ctor with arguments was available, a warning should be produced with no code fix.

**Comment by rockfordlhotka** [comment]
[‎9/‎9/‎2015 6:19 PM] Jason Bock: 
OK, like I said in email, I figured out the issue. I'll get it fixed tonight. BTW....are you SURE you want me to give warnings for ctors with arguments on commands? That seems like that would be annoying, esp. since commands can be created that way
I would find it annoying :)
[‎9/‎9/‎2015 6:19 PM] Rocky Lhotka: 
I'm not sure
ok, I am sure I don't want the warnings
[‎9/‎9/‎2015 6:19 PM] Jason Bock: 
:)
[‎9/‎9/‎2015 6:19 PM] Rocky Lhotka: 
but probably not just in commands
[‎9/‎9/‎2015 6:19 PM] Jason Bock: 
I'll adjust that
really
?
[‎9/‎9/‎2015 6:20 PM] Rocky Lhotka: 
another way to implement a common pattern is using readonlybase objects as a read-command
[‎9/‎9/‎2015 6:20 PM] Jason Bock: 
it's OK for businessbases?
oh
I can take that code out
[‎9/‎9/‎2015 6:20 PM] Rocky Lhotka: 
so I think just check it for businessbase, businesslistbase, and dynamiclistbase
[‎9/‎9/‎2015 6:20 PM] Jason Bock: 
AH
ok
[‎9/‎9/‎2015 6:20 PM] Rocky Lhotka: 
and businessbindinglistbase
[‎9/‎9/‎2015 6:21 PM] Jason Bock: 
but the no-arg ctor is for all stereotypes, correct?
[‎9/‎9/‎2015 6:21 PM] Rocky Lhotka: 
all the editable base types basically
yes - that is required for serialization
[‎9/‎9/‎2015 6:21 PM] Jason Bock: 
ok

**Comment by JasonBock** [comment]
@rockfordlhotka why doesn't DynamicListBase inherit from IBusinessObject?

**Comment by rockfordlhotka** [comment]
Probably an oversight, I guess I don't see why it *wouldn't*.

**Comment by JasonBock** [comment]
I can work around it for now when I check if it's a stereotype. Just thought you may want to add that for completeness's sake.

**Comment by swegele** [comment]
We do not support any of the async clients and our business layer is always in FullDotNet.  
I purposely have not implemented the public constructor issue that arose way back with silverlight.  All of our constructors are private.  
The "error" if no public constructor scared me a bit.  Is that just an analyzer error or are you saying the code wouldn't compile?  Sorry for my ignorance, as I haven't used the analyzer stuff yet.

**Comment by rockfordlhotka** [comment]
I believe you can disable specific analyzers - @JasonBock can say for sure.

**Comment by JasonBock** [comment]
Yes, analyzers can be turned off.

@swegele, is there an issue if you don't have a public constructor, other than a fear that someone may create the BO directly through that constructor.

**Comment by swegele** [comment]
Cool that is good to know guys.  Thankyou.
@JasonBock  yes that is precisely it.  Part of what I love about CSLA is the factory pattern and the abstracted complexity.  The outside consumer of BLs sees their business domain and not a bunch of gobbly-gook framework related stuff.  I like to know when someone is in my house...particularly that they came through the welcome door.  I felt like the silverlight requirement of a public constructor was an unfortunate compromise.  I also felt that needing publicly viewable PropertyInfo's was a kick in the gut.  Got past those both because we have a WebAPI wrapper around BL for those who need async/client functionality.

**Comment by JasonBock** [comment]
There is another analyzer I'm considering to let you know when someone is calling a ctor on a BO, which seems only valid in the object factory approach. Anywhere else doesn't seem valid. Would that help?

**Comment by swegele** [comment]
@JasonBock - That is a decent passive approach.  In our case the BL will be published/consumed by 3rd party devs at clients.  Assuming they cared to learn or were looking...they would see your proposed analyzer rule.  But I always go back to the addage "If you hand them a loaded gun..."  Personally if I had to have public ctor then I would do the old tried and true private bool _isInit kind of thing to stop illegal entries into my object.

**Comment by Jaans** [comment]
Thanks for the hard work everyone!

If I may chime in with my 2c?
We use the factory with private constructors throughout, in fact we use tools that help build our business objects, and when we are creating the business objects for platforms that require it (like Silverlight) they get a public constructor, but the corresponding server side mobile .NET business object still has a private constructor.

My personal preference would be for private constructors - no matter how much training / documentation, etc. there will always be someone internal or external 3rd party who tries to do something exotic with a CSLA business object, purely because they don't know or work with them on a regular basis. So for that reason, I'm in the "given enough rope" category :-)

As for command objects, similar thing. We employ a private constructor, sometimes with arguments supplied by the public factory.

**Comment by swegele** [comment]
Ditto @Jaans regarding the command objects with parameters in private ctors

**Comment by JasonBock** [comment]
I appreciate the feedback on this. Ultimately, I defer to @rockfordlhotka's opinion on what should be done with analyzers. At this point we're getting into a better groove with them in that:

* I'll post an idea on the forums to see if it's a good one to write for an analyzer
* If, after any discussion, it still makes sense, it'll be moved into a real "issue" on the CSLA site
* I'll work on it, and commit it

With this one, I talked to Rocky a lot about if this makes sense, and his response was yes, your no-argument ctor should always be public. I do get the points being made here, but a client will always be able to circumvent what's in place if they really want to and know what they're doing :). Granted, making something private is a deterrent, but there are ways to easily get around that too.

**Comment by Jaans** [comment]
Of course - thanks for the context. 
Figured I'd throw our usage scenario in the ring as I had always taken to the private default constructor as a best-practice from Rocky from the "Business Objects" books days. 

I'll chew on the "public .ctr is the new black" position for ourselves - I haven't checked yet, but can some analyzers be disabled while others be left enabled when it comes from the same source (CSLA Analyzers that is)?

**Comment by rockfordlhotka** [comment]
We're also discussing adding an analyzer that would warn if someone writes code that uses a ctor directly - basically the counterpoint to the reality that those ctors need to exist.

In other words, we'll help make sure they exist so serialization works, and then we'll help make sure nobody uses them :smile:

**Comment by GillesBer** [comment]
My 2 cents.
Getting some analyzer warning seems great. I used to add an [Obsolete("Use factory method", true)] attribute on our public constructors. This helps education of newcomers!
Silverlight was not the only situation in which public constructors were required. 
With Winform, we faced some problem binding our collection class (with no constructors) to ITypedList (using the Type).
