### ISSUE TITLE
Analyzer: Using [RunLocal] On Child_XYZ Operations

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#392]
[RunLocal] only has meaning for DataPortal_XYZ operations, not Child_XYZ operations. If the attribute is put on a Child_XYZ method, create a warning with a code fix to remove it.

**Comment by jonnybee** [comment]
[RunLocal] is also valid on ObjectFactory methods that is called through root DataPortal. Will this be handled correct by the Analyzer?

**Comment by JasonBock** [comment]
Jonny, I always forget about ObjectFactory as I never use it :). It shouldn't be an issue to add that support.

**Comment by JasonBock** [comment]
Just as a reminder to @rockfordlhotka to add a code example that illustrates what is correct usage of `[RunLocal]` and what isn't (or is unnecessary).

**Comment by rockfordlhotka** [comment]
@JasonBock I sent you the _Data Access_ book - page 57 has the info.

That said, I think we could make an argument that folks using the ObjectFactory approach chose that path because it allows complete control, without any of the guardrails or guidance normally provided by the data portal - so perhaps we _shouldn't_ have the analyzers looking at that code?

**Comment by JasonBock** [comment]
FYI this doesn't need to be done when using the ObjectFactory approach.
