### ISSUE TITLE
Provide More Information in UndoException

### ISSUE THREAD

**Issue by JasonBock** [MarimerLLC/csla#472]
Today at a client they showed me an issue with their code that was generating this exception, and the only piece of information we got was:

```
Message=Edit level mismatch in CopyState
```

We had no idea which object was the problem. It would be nice if this exception could contain (either in the `Message` or custom properties):
- The name of the type of the object that caused this issue
- A `ToString()` dump of that object (and maybe this could be optimized out as a configuration switch)
- The type name of the parent if it isn't null (with a `ToString()` dump similar to the previous bullet point)
- The `EditLevel` value CSLA was expecting, and what it was on the object that caused the issue.

**Comment by tfreitasleal** [comment]
hear! hear!

I know this exception quite well. The [Caliburn.Micro port for Windows Forms and Visual WebGUI](http://mvvmfx.codeplex.com/) includes a CSLA .NET adapter (ViewModelBase, etc). This adapter doesn't use `System.Windows.Forms.BindingSource` but binds directly visual elements to business objects and collections. So the well known Windows Forms rules of binding/unbinding to a `BindingSource` don't apply. I had to figure out how to do it and received dozens of `Edit level mismatch` exceptions in the process.

I agree that is important to include
* The name of the type of the object that caused this issue

but in the light of my past experience, I think it's also important to include some information on the mismatched edit levels, something like the object Edit level and the parent Edit level and some hint on why there is a mismatch.

I remember quite well having to set breakpoints in CSLA source code in order to understand what was going wrong. I know that if one follows the rules, one doesn't need this kind of information. But sometimes it's not possible to follow the rules and when this happens, you need all the information you can get.

**Comment by rob-v** [comment]
PR #718
