### ISSUE TITLE
CSLA 4.6.300 WIN RT Issue "OnDeserializedHandler"

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#539]
[CSLA 4.6.300]
I am Getting the XYZ List for  following project type 
:+1: UWP - working
:+1: WPF-working
:+1: Android-working
 :+1: IOS-working
But I am facing the issue with Fetch method when I call into WinRT Project
:negative_squared_cross_mark: :  ### WinRT -**Csla.Core.ExtendedBindingList`1'** in assembly 'Csla, Version=4.6.300.0, Culture=neutral, PublicKeyToken=93be5fdc093e4c30' has method 'OnDeserializedHandler'  I am getting this error

**Comment by rockfordlhotka** [comment]
@SachinPNikam I am hoping you are willing to help me debug/test this issue, as I have no Win8 devices anymore. Are you able to get this error on a Win10 device, but when building a WinRT app?

**Comment by rockfordlhotka** [comment]
Related to #535 and #526

**Comment by rockfordlhotka** [comment]
Digging into this I am finding some odd behaviors. Code that used to work that doesn't anymore.

I strongly suspect that Roslyn and/or .NET 4.6 have changed some behaviors in the runtime code of WinRT. Most notably, I think that mscorlib in WinRT now does contain some non-public implementations of `SerializableAttribute` and the concept of a deserialization handler - where these things didn't exist in the original WinRT on Windows 8 or 8.1.

The new `IsSerializable` implementation looks like this:

```csharp
      var tinfo = t.GetTypeInfo();
      var result = tinfo.CustomAttributes.Where(r => r.AttributeType.FullName == "System.SerializableAttribute");
      return (result != null && result.Count() > 0);
```

Notice the string compare for the typename. This is because I'm sometimes getting the `Serializable` attribute from CSLA, and sometimes from mscorlib (even though there is no such attribute in the mscorlib public surface area). To overcome this issue I've switched to a string comparison rather than relying on the actual Type.

**Comment by rockfordlhotka** [comment]
@SachinPNikam if you could try against the beta version I put into NuGet and see if it works for you I would appreciate the help.

**Comment by SachinPNikam** [comment]
Sure rocky  ...I will try the against beta version .

**Comment by SachinPNikam** [comment]
:+1: Now I am getting the result in  WinRT Also

WIN RT Issue "OnDeserializedHandler" #539 Fixed

Thank you so much Rocky !!!
