### ISSUE TITLE
Switch GetPropertyListCache to use ConcurrentDictionary 

### ISSUE THREAD

**Issue by nico159** [MarimerLLC/csla#565]
Hi,
I'm new to csla, and while reading its code I found that _GetPropertyListCache(Type objectType)_ is not correctly handling the case of reading from _PropertyInfoCache_ while another thread is modifying it.

A thread can be executing _found = cache.TryGetValue(objectType, out list)_ while another is holding the lock on _cache_ and excecuting _cache.Add(objectType, list)_ leading to a race condition.

While the code is trying to protect itself from a race condition catching all exceptions and fallback to the slow path, .Net Dictionary make no guarantees on what will happens in such case.
Personally I think that in the specific case with current Dictionary implementation, that would be possible for the instructions to be reordered in a such way that for _TryGetValue_ when excecuted in parallel with a _Add_ with the same key, to return true and null as output parameter value.

A simple fix would be simply remove this double-checked locking optimization, and maybe evaluating the use of a ConcurrentDictionary.

**Comment by rockfordlhotka** [comment]
This question/concern comes up every 2-3 years. The pattern used here is well established and has been in use in CSLA and many other places for over a decade, so it is a pretty safe bet that there's no issue at present.

I do agree that switching to ConcurrentDictionary is a better solution. I haven't checked recently, but last time I looked into this not all the .NET platforms supported by CSLA had that type, which is why we didn't switch to it (because we'd still have to maintain the older approach for those other platforms and that introduces unnecessary complexity).

It is certainly something to consider though - if that type exists consistently across all our supported platforms it would be simpler to use.
