### ISSUE TITLE
Unable to cast object of type 'Csla.Data.ContextManager` with Same Database

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#592]
****Unable to cast object of type '**# Csla.Data.ContextManager`1[**e2.FSM.DAL.Lib.FSMEntitiesDataContext]' to type **'Csla.Data.ContextManager`1[e2.FSMRATE.DAL.Lib.FSMRatingEntitiesDataContext]'.**

**Comment by jonnybee** [comment]
Hi, 
It wont help you that the contexts uses the same database. You have 2 different context!!
One is  called FSMEntititesDataContext and the other is FMSRatingEntitiesDataContext. 

In order to use more than one datacontext you must use named contexts (label) as otherwise they will use the same default name internally.
