### ISSUE TITLE
System.NotSupportedException: Cannot deserialize type 'Csla.Rules.BrokenRule' 

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#641]
following error I am getting when UWP Application- Build in Release Mode....(I am not getting this error in Debug Mode)

Severity	Code	Description	Project	File	Line	Suppression State
Error		## **## System.NotSupportedException: Cannot deserialize type 'Csla.Rules.BrokenRule' because it contains property 'RuleName'** which has no public setter.

![image](https://cloud.githubusercontent.com/assets/17121653/18314141/5e3f3000-752f-11e6-8ffb-cd736d619573.png)

**Comment by rockfordlhotka** [comment]
I'm pretty sure what you are seeing is "expected behavior" by the .NET Native compiler - it is optimizing out code that it thinks you don't need. You must tell the compiler not to optimize Csla.dll.

This _should_ be happening automatically due to this file in the UWP project:
https://github.com/MarimerLLC/csla/blob/master/Source/Csla.Uwp/Properties/Csla.Uwp.rd.xml

But you can add a similar file to your exe project to force the issue.

**Comment by SachinPNikam** [comment]
Thanks You So much RockY for Your Valuable Reply !!!
