### ISSUE TITLE
OnlyUseCslaPropertyMethodsInGetSetRule incorrectly warning with non-managed backing field

### ISSUE THREAD

**Issue by michaelcsikos** [MarimerLLC/csla#655]
I have a property that is using a local member variable and the OnlyUseCslaPropertyMethodsInGetSetRule is displaying. The property looks like this:

```
public bool BoolValue
{
    get { return GetProperty(BoolValueProperty, m_boolValue); }
    set
    {
        switch (DataType)
        {
            case DataTypeEnum.Bool:
                SetProperty(BoolValueProperty, ref m_boolValue, value);
                break;
        }
    }
}
```

I'm using CSLA version 4.6.500.

**Comment by jonnybee** [comment]
The warning is correct as you are not only using Csla PropertyMethods. 

This is the correct code: 

	public bool BoolValue
	{
		get { return GetProperty(BoolValueProperty, m_boolValue); }
		set { 	SetProperty(BoolValueProperty, ref m_boolValue, value); }
	}

**Comment by michaelcsikos** [comment]
This is not using a managed backing field. Since when have we not been allowed to put any business logic in our business object properties? It's very common to have statements before and after a SetProperty() call.

**Comment by rockfordlhotka** [comment]
Starting with CSLA 4 and the new rules engine we _strongly_ discourage putting any code in a setter besides the call to SetProperty. Code you would have written in the setter should be implemented as rules.

The behavior you are seeing is by design.

**Comment by michaelcsikos** [comment]
Is that explained in the _UsingCsla4-02-Objects.pdf_ e-book? I just had a quick scan through the _Property Declarations_ section and couldn't find it.

**Comment by rockfordlhotka** [comment]
Probably not explained as strongly as was appropriate.

**Comment by rockfordlhotka** [comment]
If you feel that you really do need to write code in the setter then you can disable the analyzer warning, either globally or via a pragma statement on a per-property basis.

**Comment by michaelcsikos** [comment]
OK. Is the main reason for the recommendation to do with serialisation? Is the recommendation _less_ strong if we're not targeting Silverlight or WP?

**Comment by rockfordlhotka** [comment]
Using private backing fields instead of managed backing fields can affect serialization.

Putting non-standard code in a setter affects code maintainability, consistency, and the ability for us to enhance features of CSLA over time without breaking people's code.

If your property declarations are all 100% standard, then properties become (effectively) declarative code, which means they are far easier to maintain, and can be created/destroyed without any real effort (e.g. using the `cslaprop` snippet you can write a typical property in less than a second). That allows you to focus on the code that matters - the business and authorization rules, and interactions between objects in your graph.

**Comment by tfreitasleal** [comment]
Property setters raise the PropertyChanged event and that has an incredible value.
It's quite tempting to put some format or convert code on the setter. I know, I've been there. :)

Suppose I need a date formatted in a particular way. Why not do it in the setter? Rocky just explained that part.

My point is quite different. If you are using data binding, it surely supports a convert or format handler. XAML does, Web Forms also, even Window Forms can handle it. So why use the propert setter?

**Comment by michaelcsikos** [comment]
If we use only standard setter code, what is the recommended way to raise `OnPropertyChanged` for read-only dependent properties? A trivial example:

```
private static PropertyInfo<int> NumberProperty
            = RegisterProperty<int>(p => p.Number, StringsBiz.Number);
public int Number
{
    get { return GetProperty(NumberProperty); }
    set
    {
        SetProperty(NumberProperty, value);

        // NOT RECOMMENDED:
        OnPropertyChanged(NumberDisplayProperty);
    }
}

private static PropertyInfo<string> NumberDisplayProperty
            = RegisterProperty<string>(p => p.NumberDisplay, StringsBiz.Number);
public string NumberDisplay
{
    get
    {
        int number = GetProperty(NumberDisplayProperty);

        return number.ToString("000");
    }
}
```

Adding a `new Dependency(NumberProperty, NumberDisplayProperty)` does not seem to trigger `OnPropertyChanged` for `NumberDisplay`.

This could be done by overriding `OnPropertyChanged(IPropertyInfo propertyInfo)` and then switching on `propertyInfo` but that can become unwieldy for a more complex class.

**Comment by jonnybee** [comment]
Adding a Dependency rule should raise OnPropertyChanged for the NumberDisplayProperty when the NumberProperty is changed. Remember - this is only done when the NumberProperty is changed - or BusinessRules.CheckRules is called.

But - that dependes on the CslaPropertyChangeMode setting. Default is Xaml (so will raise OnPropertyChanged for all Properties). But when this is set to Windows you wil lonly get PropertyChanged for the "primary property". 

    protected virtual void CheckPropertyRules(IPropertyInfo property)
    {
      var propertyNames = BusinessRules.CheckRules(property);
      if (ApplicationContext.PropertyChangedMode == ApplicationContext.PropertyChangedModes.Windows)
        OnPropertyChanged(property);
      else
        foreach (var name in propertyNames)
          OnPropertyChanged(name);
    }
  
I would recommend to add the DependencyRule with Priority = -1 so that it is run before the other validation rules. If one of the other rules on NumberProperty shortcircuits the RuleEngine then the Depency may not be called.

**Comment by michaelcsikos** [comment]
Ah, I see. This is a WinForms app, so the PropertyChangedMode is indeed set to Windows.

**Comment by jonnybee** [comment]
Yep. WindowsForms databasing can be very confusing. 

When a BO raise OnPropertyChanged - all Properties EXCEPT the property that was changed will be refreshed in the UI. That's the reason there is a Csla.Windows.BindingSourceRefresh that will make sure to also refresh the property that was changed in the UI. 

Hence - it would only severly slow down the UI of a WinForms Application if the PropertyChanged event was raise for each property (as one should in all other DataBinding technologies).
