### ISSUE TITLE
For .NETStandard use Default SerializableAttribute

### ISSUE THREAD

**Issue by amasasi** [MarimerLLC/csla#676]
For .NETStandard 1.6 use Default SerializableAttribute from System.Runtime.Serialization.Formatters . For now I fail to use csla with other libraries such as RestSharp as there is conflict

**Comment by rockfordlhotka** [comment]
I agree that this needs to be addressed. Right now it is a no win situation, because multiple frameworks need the attribute, and none of us can give up our implementation without a shared common implementation to utilize.

See this CSLA issue: https://github.com/MarimerLLC/csla/issues/407

and this Autofac issue: https://github.com/autofac/Autofac/issues/782

I'm sure there are other examples beyond these two (and now RestSharp) where conflicts exist.

Over the next couple years this should start to be resolved. NetStandard 2.0 will eventually be supported by all modern platforms (possibly by the end of 2017), and then as everyone moves their apps onto modern platforms over the next 2-10 years they'll be able to use updated frameworks that use the new netstandard `Serializable` attribute.

**Comment by dazinator** [comment]
I think this can now be closed as per recent PR's..
