### ISSUE TITLE
This line in project tracker sample looks odd

### ISSUE THREAD

**Issue by dazinator** [MarimerLLC/csla#687]
Just browsing around the project tracker sample, and assuming I can read code correctly today, think I spotted something very minor:

https://github.com/MarimerLLC/csla/blob/master/Samples/ProjectTracker/ProjectTracker.BusinessLibrary.Shared/Admin/RoleEdit.cs#L77

**Comment by rockfordlhotka** [comment]
It does look like the `id` parameter should flow through doesn't it?

**Comment by fujiiface** [comment]
Shouldn't it also be a FetchChild?

**Comment by rockfordlhotka** [comment]
@tfreitasleal has made a lot of changes via #763 - is this resolved now?

**Comment by tfreitasleal** [comment]
That's beyond scope :)
Seriously, I didn't look at the files in the admin folder.

**Comment by tfreitasleal** [comment]
The line looks odd, since the method receives a parameter that isn't used for anything at all. But I'm afraid that's not the point. The whole method 

`public static RoleEdit GetRole(int id)`

is useless since there is no matching Child_Fetch method. So I propose to remove this overload leaving only the overload

`public static RoleEdit GetRole(object data)`

While the former method isn't used anywhere, the later is used by `RoleEditList` class and also the new `RoleEditBindingList` class.

@rockfordlhotka please assing this issue to me.
