### ISSUE TITLE
BusinessBase Exposes a Save Method in .NET Core Projects

### ISSUE THREAD

**Issue by rabidkitten** [MarimerLLC/csla#710]
Updated by @rockfordlhotka

As noted later in this thread, the issue is that BusinessBase exposes a sync `Save` method and BusinessListBase does not. Either .NET Core should or should not support sync methods like this, but in any case it needs to support async methods.

Original text from @rabidkitten:

Using CSLA-Core 4.6.500 (the latest at the time of this writing). 

Classes that inherit BusinessListBase do not expose a .Save method when used in a .NET Core assembly. I am getting around this by using .SaveAsync(). Objects that implement BusinessBase have the Save method. In a non-.NET Core assembly, the Save method is visible.

**Comment by rabidkitten** [comment]
No longer using the CSLA.

**Comment by rockfordlhotka** [comment]
I'm reopening this issue, as it might be a bug - there should be symmetry between the two base classes and their `Save` method options.

**Comment by rob-v** [comment]
The BusinessListBase.Save method has this conditional compilation: #if !(ANDROID || IOS) **&& !NETFX_CORE** I assume it can be removed to support Save for .NET Core projects.

I didn't finish my test, because I assume to load/reference CSLA for .NET Core projects I need VS 2017.

**Comment by rockfordlhotka** [comment]
This is a bug - the history is that UWP doesn't support synchronous IO operations, and it was the first ".NET Core" platform - so when I added support for UWP I had to remove the sync `Save` operations.

I actually think the bug here is that I didn't block out the sync method on `BusinessListBase`, not that it is missing from `BusinessBase`.

It remains to be seen whether I'll choose to support any sync data portal behaviors in .NET Core, given that the world is clearly moving to async overall.

**Comment by rockfordlhotka** [comment]
I am going to close this, as the problem no longer exists in NS 2.0 - the codebase for NS 2.0 and other platforms is much more normalized than it could be in NS 1.x.

If someone is truly stuck on NS 1.x they can use the workaround noted above.
