### ISSUE TITLE
Issue with  Serializable, SerializableAttribute UWP

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#744]
I updated the my library project  with CSLA-Core 4.6.602 Version
but I am getting the error with all uwp library project ..give me the suggestion to resolve this issue.
	
The type or namespace name '**SerializableAttribute**' could not be found (are you missing a using directive or an assembly reference?) 	
	The type or namespace name '**Serializable**' could not be found (are you missing a using directive or an assembly reference?)

**Comment by rockfordlhotka** [comment]
Thank you for finding this - I think the issue is that I didn't add a dependency to the NuGet package to force a new Microsoft package into your project.

The workaround is easy in the meantime - just add the `System.Runtime.Serialization.Formatters` package from NuGet to your package - that'll add the Microsoft attribute for you.

**Comment by SachinPNikam** [comment]
Thank you rocky for your quick valuable reply!!!
