### ISSUE TITLE
Use object Identity as ref id in MobileFormatter

### ISSUE THREAD

**Issue by rockfordlhotka** [MarimerLLC/csla#758]
In a code review of the new `GraphMerger` implementation, @JasonBock suggested that the MobileFormatter could maybe use the new `IBusinessObject.Identity` property value as the reference id value for each object as it is serialized.

Right now the MF generates a unique refid for each object it serializes, and that refid value is part of the serialization stream. The new `Identity` property is also a unique value for each object in the graph, and it also is part of the serialization stream. Both values are `int`, so it seems reasonable that both values aren't necessary.

**Comment by tfreitasleal** [comment]
This means `IBusinessObject.Identity` won't consume extra bandwidth.

Quoting #755 PR
> The GraphMerger class implements code to merge one graph into another, working against BusinessBase and BusinessListBase types and object graphs composed of those two types. No other base classes are currently supported

If I understand it correctly, the `GraphMerger `implementation excludes `CommandBase`, `CriteriaBase`, `ReadOnlyBase`, etc.
I presume this change is strictly a `MobileFormatter `change and won't change anything on the `GraphMerger  `side.

**Comment by StefanOssendorf** [comment]
The assumption `he new Identity property is also a unique value for each object in the graph` is wrong.
Currently an `Identity` value must only be unique within lists (as discovered/learned in #3581 ) and is only unique within such. 

So we either drop this issue or we have to invest time into coming up with a solution to make an identity value unique within a whole object graph.

And IMHO the latter one will be a PITA because we have to traverse the _whole_ graph for each property set of a BO type or adding a child to a list. That won't be easy I guess.

**Comment by rockfordlhotka** [comment]
Good point, thank you for calling this out.
