### ISSUE TITLE
Not able to link any form event if class is inherited from CommandBase

### ISSUE THREAD

**Issue by DevinderMCA** [MarimerLLC/csla#812]
I have upgrade my code from csla 3.6.3 to csla 4.6.5

DataPortal_Execute method executed after calling the DataPortal.BeginExecute method of CommandBase class. I have code written in DataPortal_Execute to do some processing and update window form about the progress and completion of the task during that process.

Now If form's events are attached to class inherited from CommandBase class then DataPortal_Execute does not called after calling DataPortal.BeginExecute. The movement I comment the code that attach events to class then everything run fine. 

I also tried to mark events as Non Serializable but in that case I lost my reference to form's events as after deserialization events variable are set to null and there is no way to restore them back.

One solution I found to this problem is to use static Collection and GUID as key and mark events as non Serializable. I have generated new GUID for each instance and then before calling DataPortal.BeginExecute events members are added to static collection with key and when DataPortal_Execute method is called then I fetch events from collection for current key and then remove that key from collection. 

In this way temporary I am able to run my code. But I want to know the best way to resolve this issue.

**Comment by DevinderMCA** [comment]
Please Help in this issue. 
I know there are posts regarding this issue in the past and there are many recommendations to resolve this issue. I had gone through all of them but nothing able to resolve this issue as reason mentioned in above issue.

**Comment by rockfordlhotka** [comment]
@DevinderMCA, sorry for not responding sooner - you'd have better luck asking this sort of question in the [cslaforum](https://github.com/marimerllc/cslaforum) repo, which is far more active. This repo is used for managing the actual project issues, not Q&A.

To answer your question in at least one way, what you are doing is not supported. The `DataPortal_XYZ` methods are assumed to run on a server, so if they try to directly interact with any client-side resources (like the UI) that entirely breaks the CSLA architecture.

If you were able to make this work in the past that was a (fortunate?) thing for you, but is absolutely not something that is recommended or supported, and it is very likely that over time we've made it difficult or impossible to do such a thing. Not on purpose, but just because it isn't a factor in the architecture, so we don't think about enabling such a thing.
