### ISSUE TITLE
Need a net46 folder adding to the nuget lib folder

### ISSUE THREAD

**Issue by j055** [MarimerLLC/csla#816]
Need a `net46` folder adding to the nuget `lib` folder so we get the right assemblies with projects targeting 46 and above (for AsyncLocal<T> support). 

Currently `CSLA-Core.4.7.100-Beta-17120701` Nuget references the net45 assemblies in projects targeting .NET Framework 4.6 and above.

I think this explains things a bit better than I can:
https://docs.microsoft.com/en-us/nuget/create-packages/supporting-multiple-target-frameworks

**Comment by rockfordlhotka** [comment]
There actually _is_ a `net46` folder in NuGet in the CSLA-Core package.

It might be that the Csla.Net.4.6 project isn't referencing the latest assemblies or something?

**Comment by j055** [comment]
1. Create new class lib project in Visual Studio 2017 (v15.6.3), targeting 4.6.2.
2. Run 'Install-Package CSLA-Core -Version 4.7.100-Beta-17120701' in package manager console
3. Under references in the project right-click on CSLA-Core and select view in object browser
4. Select Csla in the list. Assembly is 'C:\Users\andre\.nuget\packages\csla-core\4.7.100-beta-17120701\lib\net45\Csla.dll'

The 'lib' folders are:

C:\Users\andre\.nuget\packages\csla-core\4.7.100-beta-17120701\lib\net40 
C:\Users\andre\.nuget\packages\csla-core\4.7.100-beta-17120701\lib\net45 
C:\Users\andre\.nuget\packages\csla-core\4.7.100-beta-17120701\lib\netstandard2.0 

You've since released '4.7.100-R18031402' however there is still a problem. 'netstandard2.0' is missing. Lib folder contains the following:

C:\Users\andre\.nuget\packages\csla-core\4.7.100-r18031402\lib\net40 
C:\Users\andre\.nuget\packages\csla-core\4.7.100-r18031402\lib\net45 
C:\Users\andre\.nuget\packages\csla-core\4.7.100-r18031402\lib\net46 
C:\Users\andre\.nuget\packages\csla-core\4.7.100-r18031402\lib\portable-net45+win8+wpa81 
C:\Users\andre\.nuget\packages\csla-core\4.7.100-r18031402\lib\portable-net45+win8+wpa81+wp8

**Comment by rockfordlhotka** [comment]
The CSLA-Core package no longer has any NS2 assembly. There's now also a CSLA-Core-NS package that only has the NS2 assembly as per PR #817 and issue #793.

This is unfortunately necessary at the moment because the `NonSerialized` attribute in full .NET is apparently missing some type forwarding information, so classes in an NS2 assembly that use that attribute can't be used at runtime within full .NET 😭 

CSLA uses that attribute so it can do cleanup on deserialization of each object graph.

The result is that, until that issue in full .NET is addressed, there's no way to use NS2 assemblies in full .NET when using CSLA.

My workaround at the moment is to have two "families" of CSLA - the full .NET family and the "modern" family for all other .NET runtimes.
