### ISSUE TITLE
Principal must be of type BusinessPrincipal, not Nothing error is getting inside ThreadPoolTimer handler

### ISSUE THREAD

**Issue by SachinPNikam** [MarimerLLC/csla#833]
hi,
updated to CSLA.UWP 4.7.100

I am getting the Csla.ApplicationContext.User is null in ThreadPoolTimer usecase.
so i am getting the  "Principal must be of type BusinessPrincipal, not Nothing" 

```c#
 ThreadPoolTimer.CreateTimer(itemCacheRefreshStart, TimeSpan.FromSeconds(0));

 private async void itemCacheRefreshStart(ThreadPoolTimer timer)
   {
     //here Csla.ApplicationContext.User  is null
    //outside this scope Csla.ApplicationContext.User is not null
     await itemCacheRefreshFull();         
   }

```

**Comment by SachinPNikam** [comment]
hi Rocky..
It is Uwp Project I referenced CSLA.UWP  .runtime NetCore.
this code working as it is in Previous version of CSLA.
temporary I did path work i am not using that ThreadPoolTimer

**Comment by rockfordlhotka** [comment]
This may be small consolation, but this is the result of a known breaking change made in 4.7.100

https://github.com/MarimerLLC/csla/issues/729

The change makes scenarios like yours a bit more complex, but brings the behavior of CSLA in line with the expected behavior of per-thread state values so it acts like .NET instead of our own weird behavior.
